-- =====================================================================================
-- CRM NOVA ERA — ESTRUTURA LEGADA MÍNIMA PARA STAGING (schema-only)
-- =====================================================================================
-- Executar UMA vez em um projeto Supabase de STAGING (NUNCA em produção diaegvfveqezispcthwk).
-- Deriva da inspeção READ-ONLY da produção: apenas a superfície que a migration Nova Era
-- referencia. SEM dados reais, SEM secrets, SEM usuários/telefones/e-mails/propostas/vendas reais.
--
-- Pré-requisitos do ambiente Supabase (já fornecidos pela plataforma; NÃO recriar aqui):
--   - schema auth + auth.uid() + auth.jwt();
--   - roles anon, authenticated, service_role, postgres;
--   - extensão pgcrypto (gen_random_uuid()).
-- No dress-rehearsal LOCAL, o arquivo 00_local_bootstrap.sql cria esses stubs antes deste.
-- =====================================================================================
\set ON_ERROR_STOP on

-- ------------------------------------------------------------------ TABELAS LEGADAS
CREATE TABLE IF NOT EXISTS public.perfis (
  id text PRIMARY KEY, nome text, permissoes jsonb, is_system boolean DEFAULT true
);
CREATE TABLE IF NOT EXISTS public.usuarios (
  id uuid PRIMARY KEY, nome text, email text, role text NOT NULL,
  permissoes jsonb, ativo boolean NOT NULL DEFAULT true, superior_id uuid
);
CREATE TABLE IF NOT EXISTS public.corretores (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id uuid REFERENCES public.usuarios(id), ativo boolean DEFAULT true
);
CREATE TABLE IF NOT EXISTS public.leads (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text, telefone text, email text, criado_em timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.negocios (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id bigint NOT NULL REFERENCES public.leads(id),
  corretor_id bigint REFERENCES public.corretores(id),
  status text NOT NULL DEFAULT 'aberto',
  criado_em timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_negocios_corretor ON public.negocios (corretor_id);
CREATE INDEX IF NOT EXISTS idx_negocios_lead     ON public.negocios (lead_id);
CREATE INDEX IF NOT EXISTS idx_negocios_stage    ON public.negocios (status);
CREATE TABLE IF NOT EXISTS public.empreendimentos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), nome text
);
CREATE TABLE IF NOT EXISTS public.unidades (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), empreendimento_id uuid REFERENCES public.empreendimentos(id)
);
CREATE TABLE IF NOT EXISTS public.visitas (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  negocio_id bigint REFERENCES public.negocios(id), created_by uuid,
  corretor_id bigint REFERENCES public.corretores(id),
  status text NOT NULL DEFAULT 'agendada', data date
);
CREATE TABLE IF NOT EXISTS public.vendas (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), vgv numeric NOT NULL DEFAULT 0, status text NOT NULL DEFAULT 'pendente'
);
CREATE TABLE IF NOT EXISTS public.venda_corretores (
  venda_id uuid REFERENCES public.vendas(id), corretor_id bigint REFERENCES public.corretores(id),
  PRIMARY KEY (venda_id, corretor_id)
);

-- ------------------------------------------------------------------ HELPERS REAIS (corpos capturados por descoberta read-only)
-- SECURITY DEFINER, STABLE, search_path=public, owner postgres (no Supabase). Owner isento de RLS
-- (FORCE ROW LEVEL SECURITY = OFF nas tabelas legadas) => leitura de negocios sem recursão.
CREATE OR REPLACE FUNCTION public.can_manage_all() RETURNS boolean
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public' AS $$
  select exists (select 1 from public.usuarios u where u.id = (select auth.uid()) and u.ativo and u.role in ('admin','executivo'));
$$;
CREATE OR REPLACE FUNCTION public.current_broker_id() RETURNS bigint
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public' AS $$
  select c.id from public.corretores c where c.usuario_id = (select auth.uid()) limit 1;
$$;
CREATE OR REPLACE FUNCTION public.manages_broker(p_corretor_id bigint) RETURNS boolean
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public' AS $$
  with me as (select u.id, u.role::text as role from usuarios u where u.id = (select auth.uid()) and u.ativo)
  select exists (
    select 1 from me cross join lateral (
      with recursive tree as (
        select id from usuarios where superior_id = me.id
        union all select u.id from usuarios u join tree t on u.superior_id = t.id
      ) select id from tree
    ) sub join corretores c on c.usuario_id = sub.id
    where me.role in ('gerente','diretor') and c.id = p_corretor_id);
$$;
CREATE OR REPLACE FUNCTION public.has_perm(p_modulo text, p_acao text) RETURNS boolean
  LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO 'public' AS $$
declare v_role text; v_uid uuid := (select auth.uid()); v_over jsonb; v_prof jsonb;
begin
  if v_uid is null then return false; end if;
  select u.role::text, u.permissoes into v_role, v_over from usuarios u where u.id = v_uid and u.ativo;
  if v_role is null then return false; end if;
  if v_role in ('admin','executivo') then return true; end if;
  if v_over is not null and v_over ? p_modulo then return (v_over -> p_modulo) ? p_acao; end if;
  select p.permissoes into v_prof from perfis p where p.id = v_role;
  if v_prof is not null and v_prof ? p_modulo then return (v_prof -> p_modulo) ? p_acao; end if;
  return false;
end $$;
GRANT EXECUTE ON FUNCTION public.can_manage_all(), public.current_broker_id(),
  public.manages_broker(bigint), public.has_perm(text,text) TO anon, authenticated, service_role;

-- ------------------------------------------------------------------ GRANTS + RLS LEGADA (equivalente à produção)
GRANT SELECT ON public.usuarios, public.perfis, public.corretores, public.leads, public.negocios,
                public.visitas, public.vendas, public.venda_corretores,
                public.empreendimentos, public.unidades TO authenticated;

ALTER TABLE public.negocios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.visitas  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendas   ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS negocios_select_scoped ON public.negocios;
CREATE POLICY negocios_select_scoped ON public.negocios FOR SELECT TO authenticated
  USING (public.can_manage_all() OR corretor_id = (SELECT public.current_broker_id()));
DROP POLICY IF EXISTS leads_select_scoped ON public.leads;
CREATE POLICY leads_select_scoped ON public.leads FOR SELECT TO authenticated
  USING (public.can_manage_all() OR EXISTS (
    SELECT 1 FROM public.negocios n WHERE n.lead_id = leads.id AND n.corretor_id = (SELECT public.current_broker_id())));
DROP POLICY IF EXISTS visitas_select_team ON public.visitas;
CREATE POLICY visitas_select_team ON public.visitas FOR SELECT TO authenticated
  USING (public.can_manage_all() OR corretor_id = (SELECT public.current_broker_id()) OR public.manages_broker(corretor_id));
DROP POLICY IF EXISTS vendas_select_own ON public.vendas;
CREATE POLICY vendas_select_own ON public.vendas FOR SELECT TO authenticated
  USING (public.can_manage_all() OR EXISTS (
    SELECT 1 FROM public.venda_corretores vc WHERE vc.venda_id = vendas.id AND vc.corretor_id = (SELECT public.current_broker_id())));

-- Perfis padrão (metadados de permissão; NÃO são dados de clientes)
INSERT INTO public.perfis (id, nome, permissoes) VALUES
  ('admin',    'Administrador', '{}'::jsonb),
  ('gerente',  'Gerente',       '{"crm":["ver","editar"]}'::jsonb),
  ('corretor', 'Corretor',      '{"crm":["ver","editar"]}'::jsonb)
ON CONFLICT (id) DO NOTHING;

SELECT 'ESTRUTURA_LEGADA_STAGING_OK' AS status;
