"use client";
import { useMemo, useState } from "react";
import type { StudioData } from "./domain";
const labels: Record<string,string>={rascunho:"Rascunho",em_revisao:"Em revisão",aprovada:"Aprovada",agendada:"Agendada",publicada:"Publicada"};
export function StudioManagerBoard({data,onOpen}:{data:StudioData;onOpen:(campaignId:string)=>void}){
 const [campaign,setCampaign]=useState("todos"),[format,setFormat]=useState("todos"),[status,setStatus]=useState("todos"),[responsavel,setResponsavel]=useState("todos"),[revisor,setRevisor]=useState("todos"),[template,setTemplate]=useState("todos"),[period,setPeriod]=useState("todos"),[sort,setSort]=useState("prazo"); const tasks=data.tasks??[]; const comments=data.comments??[];
 const now=new Date(); const filtered=useMemo(()=>data.pieces.filter(p=>{const t=tasks.find(x=>x.piece_id===p.id); const due=t?.prazo_em?new Date(t.prazo_em):null; const periodOk=period==="todos"||(period==="sem_prazo"&&!due)||(period==="vencidos"&&Boolean(due&&due<now))||(period==="hoje"&&Boolean(due&&due.toDateString()===now.toDateString())); return (campaign==="todos"||p.campaign_id===campaign)&&(format==="todos"||p.formato===format)&&(status==="todos"||p.status===status)&&(responsavel==="todos"||t?.responsavel_id===responsavel)&&(revisor==="todos"||t?.revisor_id===revisor)&&(template==="todos"||data.versions.find(v=>v.id===p.current_version_id)?.template_version_id===template)&&periodOk;}),[data.pieces,data.versions,tasks,campaign,format,status,responsavel,revisor,template,period]);
 const ordered=[...filtered].sort((a,b)=>sort==="status"?a.status.localeCompare(b.status):(tasks.find(x=>x.piece_id===a.id)?.prazo_em??"9999").localeCompare(tasks.find(x=>x.piece_id===b.id)?.prazo_em??"9999"));
 return <section className="studio-section studio-manager-board"><header><div><span className="studio-eyebrow">Visão do gestor</span><h2>Board operacional</h2><p>Filtros reais, prazos, bloqueios e navegação direta.</p></div></header><div className="studio-board-filters"><select value={campaign} onChange={e=>setCampaign(e.target.value)}><option value="todos">Todas as campanhas</option>{data.campaigns.map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select><select value={format} onChange={e=>setFormat(e.target.value)}><option value="todos">Todos os formatos</option>{["feed","carousel","story","reel"].map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="todos">Todos os status</option>{Object.keys(labels).map(x=><option key={x}>{labels[x]}</option>)}</select><select value={responsavel} onChange={e=>setResponsavel(e.target.value)}><option value="todos">Responsável: todos</option>{(data.members??[]).map(x=><option key={x.id} value={x.id}>{x.nome} · {x.role??"membro"}</option>)}</select><select value={revisor} onChange={e=>setRevisor(e.target.value)}><option value="todos">Revisor: todos</option>{(data.members??[]).map(x=><option key={x.id} value={x.id}>{x.nome} · {x.role??"membro"}</option>)}</select><select value={period} onChange={e=>setPeriod(e.target.value)}><option value="todos">Qualquer prazo</option><option value="vencidos">Vencidos</option><option value="hoje">Hoje</option><option value="sem_prazo">Sem prazo</option></select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="prazo">Ordenar por prazo</option><option value="status">Ordenar por status</option></select></div><div className="studio-board-list">{ordered.map(p=>{const t=tasks.find(x=>x.piece_id===p.id);const pending=comments.filter(c=>c.piece_id===p.id&&!c.resolvido_em).length;const owner=(data.members??[]).find(m=>m.id===t?.responsavel_id), reviewer=(data.members??[]).find(m=>m.id===t?.revisor_id);return <button type="button" key={p.id} onClick={()=>onOpen(p.campaign_id)}><strong>{p.titulo}</strong><span>{owner?.nome??"Sem responsável"} / {reviewer?.nome??"Sem revisor"}</span><span>{t?.prazo_em?new Date(t.prazo_em).toLocaleString("pt-BR"):"Sem prazo"}</span><span>{t?.pendencia??"Sem bloqueio"}</span><b>{labels[p.status]??p.status}{pending?` · ${pending} comentários`:""}</b></button>})}</div></section>;
}
