-- DRAFT — NÃO APLICAR DIRETAMENTE EM PRODUÇÃO.
--
-- Contrato canônico do Funil 2 para a regra:
--   corretor solicita descarte -> gestão aprova ou rejeita -> só então o lead
--   sai da carteira. O histórico nunca é apagado.
--
-- Baseline remoto somente leitura (2026-09-19):
--   f2_descartar_lead(uuid,integer,text,text)
--   SHA-256 221449da857474a39b0fae8012ef3f487ff11f57777f7a60f21a8444ed9a610e
-- A função acima descarta imediatamente e, portanto, não atende ao contrato.

begin;

create table if not exists public.f2_descarte_solicitacao (
  id bigint generated by default as identity primary key,
  funil_lead_id uuid not null references public.f2_lead(id) on delete restrict,
  versao_lead_solicitada integer not null check (versao_lead_solicitada >= 1),
  motivo text not null references public.motivos_descarte(motivo) on update restrict on delete restrict,
  detalhe text null check (detalhe is null or length(detalhe) <= 500),
  status text not null default 'pendente'
    check (status in ('pendente', 'aprovada', 'rejeitada')),
  idempotency_key uuid not null,
  solicitada_por uuid not null,
  solicitada_em timestamptz not null default clock_timestamp(),
  decidida_por uuid null,
  decidida_em timestamptz null,
  decisao_observacao text null
    check (decisao_observacao is null or length(decisao_observacao) <= 500),
  constraint f2_descarte_solicitacao_decisao_coerente check (
    (status = 'pendente' and decidida_por is null and decidida_em is null)
    or
    (status in ('aprovada', 'rejeitada') and decidida_por is not null and decidida_em is not null)
  )
);

create unique index if not exists f2_descarte_solicitacao_idem_uidx
  on public.f2_descarte_solicitacao (idempotency_key);

create unique index if not exists f2_descarte_solicitacao_pendente_uidx
  on public.f2_descarte_solicitacao (funil_lead_id)
  where status = 'pendente';

create index if not exists f2_descarte_solicitacao_fila_idx
  on public.f2_descarte_solicitacao (status, solicitada_em, id);

alter table public.f2_descarte_solicitacao enable row level security;
revoke all on table public.f2_descarte_solicitacao from public, anon, authenticated;
revoke all on sequence public.f2_descarte_solicitacao_id_seq from public, anon, authenticated;

create or replace function public.f2_solicitar_descarte(
  p_id uuid,
  p_versao integer,
  p_motivo text,
  p_detalhe text default null,
  p_idempotency_key uuid default null
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_role text := coalesce((select auth.role()), '');
  v_actor uuid := (select auth.uid());
  v_self bigint := public.current_broker_id();
  v_lead public.f2_lead%rowtype;
  v_existente public.f2_descarte_solicitacao%rowtype;
  v_motivo text := pg_catalog.btrim(coalesce(p_motivo, ''));
  v_detalhe text := nullif(pg_catalog.btrim(coalesce(p_detalhe, '')), '');
  v_id bigint;
begin
  if v_role not in ('authenticated', 'service_role')
     or (v_role <> 'service_role' and v_actor is null) then
    return pg_catalog.jsonb_build_object('ok', false, 'erro', 'nao_autorizado');
  end if;
  if p_idempotency_key is null then
    return pg_catalog.jsonb_build_object('ok', false, 'erro', 'idempotencia_obrigatoria');
  end if;
  if not exists (
    select 1 from public.motivos_descarte m where m.motivo = v_motivo
  ) then
    return pg_catalog.jsonb_build_object('ok', false, 'erro', 'motivo_invalido');
  end if;
  if pg_catalog.length(coalesce(v_detalhe, '')) > 500 then
    return pg_catalog.jsonb_build_object('ok', false, 'erro', 'detalhe_muito_longo');
  end if;

  -- O lock da própria linha serializa duas solicitações concorrentes para o
  -- mesmo lead. O índice parcial fecha a segunda barreira no banco.
  select * into v_lead
    from public.f2_lead
   where id = p_id
   for update;
  if not found then
    return pg_catalog.jsonb_build_object('ok', false, 'erro', 'lead_nao_encontrado');
  end if;
  if v_lead.descartado_em is not null then
    return pg_catalog.jsonb_build_object('ok', false, 'erro', 'ja_descartado');
  end if;
  if v_lead.versao is distinct from p_versao then
    return pg_catalog.jsonb_build_object(
      'ok', false, 'erro', 'versao_desatualizada', 'versao_atual', v_lead.versao
    );
  end if;
  if not (
    v_role = 'service_role'
    or public.f2_admin()
    or v_self = v_lead.corretor_id
    or public.manages_broker(v_lead.corretor_id)
  ) then
    return pg_catalog.jsonb_build_object('ok', false, 'erro', 'sem_permissao');
  end if;

  select * into v_existente
    from public.f2_descarte_solicitacao s
   where s.idempotency_key = p_idempotency_key;
  if found then
    if v_existente.funil_lead_id = p_id then
      return pg_catalog.jsonb_build_object(
        'ok', true, 'unchanged', true, 'status', v_existente.status,
        'solicitacao_id', v_existente.id
      );
    end if;
    return pg_catalog.jsonb_build_object('ok', false, 'erro', 'idempotencia_em_conflito');
  end if;

  select * into v_existente
    from public.f2_descarte_solicitacao s
   where s.funil_lead_id = p_id and s.status = 'pendente'
   order by s.id desc
   limit 1;
  if found then
    if v_existente.motivo = v_motivo
       and coalesce(v_existente.detalhe, '') = coalesce(v_detalhe, '') then
      return pg_catalog.jsonb_build_object(
        'ok', true, 'unchanged', true, 'status', 'pendente',
        'solicitacao_id', v_existente.id
      );
    end if;
    return pg_catalog.jsonb_build_object(
      'ok', false, 'erro', 'descarte_ja_pendente',
      'solicitacao_id', v_existente.id
    );
  end if;

  insert into public.f2_descarte_solicitacao (
    funil_lead_id, versao_lead_solicitada, motivo, detalhe,
    idempotency_key, solicitada_por
  ) values (
    p_id, p_versao, v_motivo, v_detalhe, p_idempotency_key,
    coalesce(v_actor, '00000000-0000-0000-0000-000000000000'::uuid)
  ) returning id into v_id;

  insert into public.f2_evento (
    funil_lead_id, tipo, titulo, detalhe, payload, criado_por
  ) values (
    p_id, 'lead_descarte_solicitado', 'Descarte enviado para aprovação',
    v_motivo,
    pg_catalog.jsonb_build_object(
      'solicitacao_id', v_id, 'motivo', v_motivo,
      'versao_lead', p_versao
    ),
    v_actor
  );

  return pg_catalog.jsonb_build_object(
    'ok', true, 'status', 'pendente', 'solicitacao_id', v_id,
    'versao', v_lead.versao
  );
end;
$function$;

create or replace function public.f2_decidir_descarte(
  p_solicitacao_id bigint,
  p_versao integer,
  p_decisao text,
  p_observacao text default null
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_role text := coalesce((select auth.role()), '');
  v_actor uuid := (select auth.uid());
  v_decisao text := pg_catalog.lower(pg_catalog.btrim(coalesce(p_decisao, '')));
  v_observacao text := nullif(pg_catalog.btrim(coalesce(p_observacao, '')), '');
  v_pedido public.f2_descarte_solicitacao%rowtype;
  v_lead public.f2_lead%rowtype;
  v_novo_status text;
begin
  if v_role not in ('authenticated', 'service_role')
     or (v_role <> 'service_role' and v_actor is null) then
    return pg_catalog.jsonb_build_object('ok', false, 'erro', 'nao_autorizado');
  end if;
  if v_decisao not in ('aprovar', 'rejeitar') then
    return pg_catalog.jsonb_build_object('ok', false, 'erro', 'decisao_invalida');
  end if;
  if pg_catalog.length(coalesce(v_observacao, '')) > 500 then
    return pg_catalog.jsonb_build_object('ok', false, 'erro', 'observacao_muito_longa');
  end if;

  select * into v_pedido
    from public.f2_descarte_solicitacao
   where id = p_solicitacao_id
   for update;
  if not found then
    return pg_catalog.jsonb_build_object('ok', false, 'erro', 'solicitacao_nao_encontrada');
  end if;

  select * into v_lead
    from public.f2_lead
   where id = v_pedido.funil_lead_id
   for update;
  if not found then
    return pg_catalog.jsonb_build_object('ok', false, 'erro', 'lead_nao_encontrado');
  end if;
  if not (
    v_role = 'service_role'
    or public.f2_admin()
    or public.can_manage_all()
    or public.manages_broker(v_lead.corretor_id)
  ) then
    return pg_catalog.jsonb_build_object('ok', false, 'erro', 'gestao_obrigatoria');
  end if;

  v_novo_status := case when v_decisao = 'aprovar' then 'aprovada' else 'rejeitada' end;
  if v_pedido.status <> 'pendente' then
    if v_pedido.status = v_novo_status then
      return pg_catalog.jsonb_build_object(
        'ok', true, 'unchanged', true, 'status', v_pedido.status,
        'solicitacao_id', v_pedido.id, 'versao', v_lead.versao
      );
    end if;
    return pg_catalog.jsonb_build_object('ok', false, 'erro', 'solicitacao_ja_decidida');
  end if;

  if v_decisao = 'aprovar' then
    if v_lead.descartado_em is not null then
      return pg_catalog.jsonb_build_object('ok', false, 'erro', 'ja_descartado');
    end if;
    if v_lead.versao is distinct from p_versao then
      return pg_catalog.jsonb_build_object(
        'ok', false, 'erro', 'versao_desatualizada', 'versao_atual', v_lead.versao
      );
    end if;

    update public.f2_lead
       set descartado_em = clock_timestamp(),
           descartado_por = v_actor,
           descarte_motivo = v_pedido.motivo,
           descarte_detalhe = v_pedido.detalhe,
           atualizado_em = clock_timestamp(),
           versao = versao + 1
     where id = v_lead.id;
  end if;

  update public.f2_descarte_solicitacao
     set status = v_novo_status,
         decidida_por = coalesce(v_actor, '00000000-0000-0000-0000-000000000000'::uuid),
         decidida_em = clock_timestamp(),
         decisao_observacao = v_observacao
   where id = v_pedido.id;

  insert into public.f2_evento (
    funil_lead_id, tipo, titulo, detalhe, payload, criado_por
  ) values (
    v_lead.id,
    case when v_decisao = 'aprovar' then 'lead_descarte_aprovado' else 'lead_descarte_rejeitado' end,
    case when v_decisao = 'aprovar' then 'Descarte aprovado pela gestão' else 'Descarte rejeitado pela gestão' end,
    v_observacao,
    pg_catalog.jsonb_build_object(
      'solicitacao_id', v_pedido.id, 'motivo', v_pedido.motivo,
      'decisao', v_decisao
    ),
    v_actor
  );

  return pg_catalog.jsonb_build_object(
    'ok', true, 'status', v_novo_status,
    'solicitacao_id', v_pedido.id,
    'versao', case when v_decisao = 'aprovar' then v_lead.versao + 1 else v_lead.versao end
  );
end;
$function$;

create or replace function public.f2_listar_solicitacoes_descarte()
returns table (
  solicitacao_id bigint,
  funil_lead_id uuid,
  versao_lead integer,
  motivo text,
  detalhe text,
  status text,
  solicitada_em timestamptz,
  corretor_id bigint,
  corretor_nome text,
  pode_decidir boolean
)
language sql
stable
security definer
set search_path = ''
as $function$
  select
    s.id,
    s.funil_lead_id,
    l.versao,
    s.motivo,
    s.detalhe,
    s.status,
    s.solicitada_em,
    l.corretor_id,
    c.nome,
    (
      coalesce((select auth.role()), '') = 'service_role'
      or public.f2_admin()
      or public.can_manage_all()
      or public.manages_broker(l.corretor_id)
    ) as pode_decidir
  from public.f2_descarte_solicitacao s
  join public.f2_lead l on l.id = s.funil_lead_id
  left join public.corretores c on c.id = l.corretor_id
  where s.status = 'pendente'
    and l.descartado_em is null
    and (
      coalesce((select auth.role()), '') = 'service_role'
      or public.f2_admin()
      or public.can_manage_all()
      or public.manages_broker(l.corretor_id)
      or (
        l.corretor_id = public.current_broker_id()
        and s.solicitada_por = (select auth.uid())
      )
    )
  order by s.solicitada_em, s.id;
$function$;

-- A antiga porta de descarte imediato deixa de ser executável por usuários.
-- O corpo é preservado temporariamente para rollback e análise de dependências.
revoke execute on function public.f2_descartar_lead(uuid,integer,text,text)
  from public, anon, authenticated;

revoke execute on function public.f2_solicitar_descarte(uuid,integer,text,text,uuid)
  from public, anon;
revoke execute on function public.f2_decidir_descarte(bigint,integer,text,text)
  from public, anon;
revoke execute on function public.f2_listar_solicitacoes_descarte()
  from public, anon;

grant execute on function public.f2_solicitar_descarte(uuid,integer,text,text,uuid)
  to authenticated, service_role;
grant execute on function public.f2_decidir_descarte(bigint,integer,text,text)
  to authenticated, service_role;
grant execute on function public.f2_listar_solicitacoes_descarte()
  to authenticated, service_role;

do $contract$
begin
  if has_function_privilege(
    'authenticated', 'public.f2_descartar_lead(uuid,integer,text,text)'::regprocedure, 'execute'
  ) then
    raise exception 'atalho de descarte imediato ainda disponível';
  end if;
  if not has_function_privilege(
    'authenticated', 'public.f2_solicitar_descarte(uuid,integer,text,text,uuid)'::regprocedure, 'execute'
  ) or not has_function_privilege(
    'authenticated', 'public.f2_decidir_descarte(bigint,integer,text,text)'::regprocedure, 'execute'
  ) then
    raise exception 'contrato de solicitação/decisão não executável pelo papel autenticado';
  end if;
end;
$contract$;

commit;

-- ROLLBACK OPERACIONAL (executar separadamente e somente após provar que não
-- há solicitações pendentes que seriam perdidas):
-- grant execute on function public.f2_descartar_lead(uuid,integer,text,text)
--   to authenticated, service_role;
-- drop function if exists public.f2_listar_solicitacoes_descarte();
-- drop function if exists public.f2_decidir_descarte(bigint,integer,text,text);
-- drop function if exists public.f2_solicitar_descarte(uuid,integer,text,text,uuid);
-- drop table if exists public.f2_descarte_solicitacao;
