export type Product = {
  id?: string;
  name: string;
  price: string;
  neighborhood: string;
  city: string;
  status?: string;
  developer?: string | null;
  area: number;
  bedrooms: number;
  parking: number;
  available: number;
  leads: number;
  priceM2: string;
  units?: number;
  media?: number;
  coverUrl?: string | null;
  draft?: boolean;
  origin?: string;
  numericPrice?: number | null;
  favorite?: boolean;
  approval?: string;
  rejectionReason?: string | null;
  mine?: boolean;
  capturedBy?: string | null;
  priceMax?: number | null;
  areaMax?: number | null;
  typologies?: string[];
  stockValue?: number;
};

export const products: Product[] = [];
