-- Decisões humanas sobre sugestões da Sara.
-- Aceitar ou recusar é auditável e nunca equivale a enviar uma mensagem.
begin;

create table if not exists public.f2_sara_decisao (
  id bigint generated by default as identity primary key,
  analise_id bigint not null unique references public.f2_sara_analise(id) on delete cascade,
  funil_lead_id uuid not null references public.f2_lead(id) on delete cascade,
  usuario_id uuid not null default auth.uid(),
  decisao text not null check (decisao in ('aceita','recusada')),
  motivo text null check (motivo is null or char_length(motivo) <= 500),
  decidido_em timestamptz not null default now()
);

create index if not exists f2_sara_decisao_lead_idx on public.f2_sara_decisao(funil_lead_id, decidido_em desc);
alter table public.f2_sara_decisao enable row level security;
revoke all on public.f2_sara_decisao from public, anon, authenticated;
grant select, insert, update on public.f2_sara_decisao to authenticated;
grant usage, select on sequence public.f2_sara_decisao_id_seq to authenticated;

drop policy if exists f2_sara_decisao_select on public.f2_sara_decisao;
create policy f2_sara_decisao_select on public.f2_sara_decisao for select to authenticated
  using (
    public.f2_admin()
    or exists (
      select 1 from public.f2_lead f
      where f.id = f2_sara_decisao.funil_lead_id
        and f.corretor_id = (select public.f2_corretor_atual())
    )
  );

drop policy if exists f2_sara_decisao_insert on public.f2_sara_decisao;
create policy f2_sara_decisao_insert on public.f2_sara_decisao for insert to authenticated
  with check (
    usuario_id = (select auth.uid())
    and exists (
      select 1 from public.f2_sara_analise a
      join public.f2_lead f on f.id = a.funil_lead_id
      where a.id = f2_sara_decisao.analise_id
        and f.id = f2_sara_decisao.funil_lead_id
        and (public.f2_admin() or f.corretor_id = (select public.f2_corretor_atual()))
    )
  );

drop policy if exists f2_sara_decisao_update on public.f2_sara_decisao;
create policy f2_sara_decisao_update on public.f2_sara_decisao for update to authenticated
  using (usuario_id = (select auth.uid()) or public.f2_admin())
  with check (usuario_id = (select auth.uid()) or public.f2_admin());

commit;
