-- Funil 2.0 — releitura contínua da carteira pela Sara.
--
-- A Sara lê o histórico confirmado pelo D-API e escolhe SOMENTE um momento
-- ativo do catálogo f2_momento_config. Ela nunca envia mensagem, cria visita,
-- proposta ou venda e nunca altera leads/negocios dos pipes de origem.
BEGIN;

CREATE TABLE public.f2_sara_config (
  id boolean PRIMARY KEY DEFAULT true CHECK (id),
  enabled boolean NOT NULL DEFAULT false,
  lote smallint NOT NULL DEFAULT 5 CHECK (lote BETWEEN 1 AND 10),
  modo_execucao text NOT NULL DEFAULT 'canary' CHECK (modo_execucao IN ('canary','completo')),
  canary_limite smallint NOT NULL DEFAULT 5 CHECK (canary_limite BETWEEN 1 AND 10),
  edge_url text NULL CHECK (edge_url IS NULL OR edge_url ~ '^https://[a-z0-9-]+\.supabase\.co/functions/v1/f2-sara-reclassificar$'),
  confianca_minima numeric(4,3) NOT NULL DEFAULT 0.650 CHECK (confianca_minima BETWEEN 0.5 AND 1),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_por uuid NULL
);
INSERT INTO public.f2_sara_config(id,enabled,lote,edge_url)
SELECT true,false,5,
  regexp_replace(edge_url,'/ncrm-sara-observer$','/f2-sara-reclassificar')
FROM public.ncrm_sara_runner_config WHERE id
ON CONFLICT(id) DO NOTHING;
INSERT INTO public.f2_sara_config(id,enabled,lote)
VALUES(true,false,5) ON CONFLICT(id) DO NOTHING;

CREATE TABLE public.f2_sara_analise (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  funil_lead_id uuid NOT NULL REFERENCES public.f2_lead(id) ON DELETE CASCADE,
  origem_negocio_id bigint NOT NULL,
  context_hash text NOT NULL CHECK (context_hash ~ '^[a-f0-9]{64}$'),
  origem text NOT NULL CHECK (origem IN ('ia','deterministica')),
  status text NOT NULL CHECK (status IN ('aplicada','mantida','revisao_humana','sem_historico','obsoleta','falha')),
  momento_anterior text NOT NULL,
  momento_sugerido text NULL,
  acao_sugerida text NULL,
  resumo text NOT NULL CHECK (char_length(btrim(resumo)) BETWEEN 3 AND 800),
  evidencias jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(evidencias)='array'),
  confianca numeric(4,3) NULL CHECK (confianca IS NULL OR confianca BETWEEN 0 AND 1),
  mensagens_consideradas integer NOT NULL DEFAULT 0 CHECK (mensagens_consideradas BETWEEN 0 AND 250),
  versao_base integer NOT NULL CHECK (versao_base > 0),
  analisado_em timestamptz NOT NULL DEFAULT now(),
  UNIQUE(funil_lead_id,context_hash)
);
CREATE INDEX f2_sara_analise_data_idx ON public.f2_sara_analise(analisado_em DESC);
CREATE INDEX f2_sara_analise_status_idx ON public.f2_sara_analise(status,analisado_em DESC);

ALTER TABLE public.f2_sara_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.f2_sara_analise ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.f2_sara_config,public.f2_sara_analise FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.f2_sara_config,public.f2_sara_analise TO authenticated;
CREATE POLICY f2_sara_config_admin_select ON public.f2_sara_config FOR SELECT TO authenticated
  USING (public.f2_admin());
CREATE POLICY f2_sara_analise_admin_select ON public.f2_sara_analise FOR SELECT TO authenticated
  USING (public.f2_admin());

-- Só devolve itens novos ou cuja conversa mudou depois da última leitura.
CREATE OR REPLACE FUNCTION public.f2_sara_elegiveis(p_lote integer DEFAULT 5)
RETURNS TABLE(
  funil_lead_id uuid, origem_negocio_id bigint, lead_id bigint, versao integer,
  etapa text, momento_codigo text, acao_codigo text, cadencia_passo smallint,
  corte_conversa_em timestamptz, ultima_reavaliacao_sara_em timestamptz,
  ultima_mensagem_em timestamptz
)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO '' AS $fn$
  SELECT f.id,f.origem_negocio_id,n.lead_id,f.versao,f.etapa,f.momento_codigo,
         f.acao_codigo,f.cadencia_passo,f.corte_conversa_em,
         f.ultima_reavaliacao_sara_em,ult.ultima_mensagem_em
  FROM public.f2_lead f
  JOIN public.negocios n ON n.id=f.origem_negocio_id
  CROSS JOIN public.f2_sara_config cfg
  LEFT JOIN LATERAL (
    SELECT max(COALESCE(m.enviado_em,m.criado_em)) AS ultima_mensagem_em
    FROM public.wa_contatos c
    JOIN public.wa_conversas v ON v.contato_id=c.id
    JOIN public.wa_mensagens m ON m.conversa_id=v.id
    WHERE c.lead_id=n.lead_id
      AND COALESCE(m.enviado_em,m.criado_em)>=f.corte_conversa_em
  ) ult ON true
  WHERE (f.ultima_reavaliacao_sara_em IS NULL
     OR ult.ultima_mensagem_em>f.ultima_reavaliacao_sara_em)
    AND (
      cfg.modo_execucao='completo'
      OR f.id IN (
        SELECT f_canary.id
        FROM public.f2_lead f_canary
        ORDER BY f_canary.criado_em,f_canary.id
        LIMIT cfg.canary_limite
      )
    )
  ORDER BY f.ultima_reavaliacao_sara_em NULLS FIRST,
           ult.ultima_mensagem_em DESC NULLS LAST,f.id
  LIMIT LEAST(GREATEST(COALESCE(p_lote,5),1),10)
$fn$;
REVOKE ALL ON FUNCTION public.f2_sara_elegiveis(integer) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.f2_sara_elegiveis(integer) TO service_role;

CREATE OR REPLACE FUNCTION public.f2_sara_registrar_classificacao(
  p_funil_lead_id uuid,
  p_versao integer,
  p_context_hash text,
  p_origem text,
  p_status text,
  p_momento_codigo text DEFAULT NULL,
  p_resumo text DEFAULT NULL,
  p_evidencias jsonb DEFAULT '[]'::jsonb,
  p_confianca numeric DEFAULT NULL,
  p_mensagens integer DEFAULT 0,
  p_prazo_sugerido timestamptz DEFAULT NULL
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO '' AS $fn$
DECLARE
  v_lead public.f2_lead%ROWTYPE;
  v_m public.f2_momento_config%ROWTYPE;
  v_cfg public.f2_sara_config%ROWTYPE;
  v_status text;
  v_prazo timestamptz;
  v_id bigint;
  v_mesmo boolean;
BEGIN
  IF p_context_hash !~ '^[a-f0-9]{64}$' OR p_origem NOT IN ('ia','deterministica')
     OR p_status NOT IN ('sugestao','sem_historico','falha')
     OR jsonb_typeof(COALESCE(p_evidencias,'[]'::jsonb))<>'array'
     OR COALESCE(char_length(btrim(p_resumo)),0) NOT BETWEEN 3 AND 800
     OR COALESCE(p_mensagens,0) NOT BETWEEN 0 AND 250 THEN
    RETURN jsonb_build_object('ok',false,'erro','contrato_invalido');
  END IF;

  SELECT * INTO v_lead FROM public.f2_lead WHERE id=p_funil_lead_id FOR UPDATE;
  IF NOT FOUND THEN RETURN jsonb_build_object('ok',false,'erro','lead_inexistente'); END IF;
  SELECT id INTO v_id FROM public.f2_sara_analise
   WHERE funil_lead_id=p_funil_lead_id AND context_hash=p_context_hash;
  IF v_id IS NOT NULL THEN RETURN jsonb_build_object('ok',true,'ja_processado',true,'analise_id',v_id); END IF;
  SELECT * INTO v_cfg FROM public.f2_sara_config WHERE id;

  IF p_status='sem_historico' THEN
    v_status:='sem_historico';
  ELSIF p_status='falha' THEN
    v_status:='falha';
  ELSIF v_lead.versao<>p_versao THEN
    v_status:='obsoleta';
  ELSE
    SELECT * INTO v_m FROM public.f2_momento_config WHERE codigo=p_momento_codigo AND ativo;
    IF NOT FOUND THEN RETURN jsonb_build_object('ok',false,'erro','momento_invalido'); END IF;
    IF p_confianca IS NULL OR p_confianca<COALESCE(v_cfg.confianca_minima,0.650)
       OR (p_origem='ia' AND p_momento_codigo<>'CADENCIA_SEM_RESPOSTA'
           AND jsonb_array_length(COALESCE(p_evidencias,'[]'::jsonb))=0) THEN
      v_status:='revisao_humana';
    ELSE
      v_mesmo:=v_lead.momento_codigo=v_m.codigo;
      v_prazo:=CASE
        WHEN v_m.codigo='RETORNO_PROGRAMADO' AND p_prazo_sugerido>now()
          AND p_prazo_sugerido<=now()+interval '30 days' THEN p_prazo_sugerido
        ELSE now()+make_interval(mins=>COALESCE(v_m.prazo_minutos,1440))
      END;
      UPDATE public.f2_lead SET
        etapa=v_m.etapa,momento_codigo=v_m.codigo,acao_codigo=v_m.acao_codigo,
        acao_rotulo=v_m.acao_rotulo,proxima_acao_em=v_prazo,
        cadencia_passo=CASE WHEN v_m.codigo='CADENCIA_SEM_RESPOSTA'
          THEN CASE WHEN v_lead.momento_codigo='CADENCIA_SEM_RESPOSTA' THEN v_lead.cadencia_passo ELSE 0 END
          ELSE v_lead.cadencia_passo END,
        ultima_reavaliacao_sara_em=now(),
        ultima_reavaliacao_resumo=left(btrim(p_resumo),800),
        versao=versao+1,atualizado_em=now(),atualizado_por=NULL
      WHERE id=p_funil_lead_id;
      INSERT INTO public.f2_evento(funil_lead_id,tipo,titulo,detalhe,payload,criado_por)
      VALUES(p_funil_lead_id,'sara_reavaliou',
        CASE WHEN v_mesmo THEN 'Sara confirmou o momento: ' ELSE 'Sara atualizou o momento para ' END||v_m.rotulo,
        left(btrim(p_resumo),500),
        jsonb_build_object('origem','sara_funil_2','momento_anterior',v_lead.momento_codigo,
          'momento_novo',v_m.codigo,'acao',v_m.acao_codigo,'prazo',v_prazo,
          'confianca',p_confianca,'context_hash',p_context_hash),NULL);
      v_status:=CASE WHEN v_mesmo THEN 'mantida' ELSE 'aplicada' END;
    END IF;
  END IF;

  -- Falha, ausência de histórico e revisão humana também encerram este contexto;
  -- uma mensagem D-API nova torna o lead elegível novamente.
  IF v_status IN ('sem_historico','revisao_humana','falha','obsoleta') THEN
    UPDATE public.f2_lead SET ultima_reavaliacao_sara_em=now(),
      ultima_reavaliacao_resumo=left(btrim(p_resumo),800),atualizado_em=now()
    WHERE id=p_funil_lead_id;
  END IF;

  INSERT INTO public.f2_sara_analise(
    funil_lead_id,origem_negocio_id,context_hash,origem,status,
    momento_anterior,momento_sugerido,acao_sugerida,resumo,evidencias,
    confianca,mensagens_consideradas,versao_base
  ) VALUES(
    p_funil_lead_id,v_lead.origem_negocio_id,p_context_hash,p_origem,v_status,
    v_lead.momento_codigo,v_m.codigo,v_m.acao_codigo,left(btrim(p_resumo),800),
    COALESCE(p_evidencias,'[]'::jsonb),p_confianca,COALESCE(p_mensagens,0),p_versao
  ) RETURNING id INTO v_id;
  RETURN jsonb_build_object('ok',true,'analise_id',v_id,'status',v_status,
    'momento_codigo',v_m.codigo,'versao',CASE WHEN v_status IN ('aplicada','mantida') THEN v_lead.versao+1 ELSE v_lead.versao END);
EXCEPTION WHEN unique_violation THEN
  SELECT id INTO v_id FROM public.f2_sara_analise
   WHERE funil_lead_id=p_funil_lead_id AND context_hash=p_context_hash;
  RETURN jsonb_build_object('ok',true,'ja_processado',true,'analise_id',v_id);
END;
$fn$;
REVOKE ALL ON FUNCTION public.f2_sara_registrar_classificacao(uuid,integer,text,text,text,text,text,jsonb,numeric,integer,timestamptz)
  FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.f2_sara_registrar_classificacao(uuid,integer,text,text,text,text,text,jsonb,numeric,integer,timestamptz)
  TO service_role;

CREATE OR REPLACE FUNCTION public.f2_sara_tick()
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path TO '' AS $fn$
DECLARE v_cfg public.f2_sara_config%ROWTYPE; v_secret text;
BEGIN
  SELECT * INTO v_cfg FROM public.f2_sara_config WHERE id;
  IF COALESCE(v_cfg.enabled,false) IS NOT TRUE OR v_cfg.edge_url IS NULL THEN RETURN; END IF;
  BEGIN
    SELECT decrypted_secret INTO v_secret FROM vault.decrypted_secrets
      WHERE name='ncrm_sara_cron_secret' LIMIT 1;
  EXCEPTION WHEN others THEN v_secret:=NULL; END;
  IF v_secret IS NULL THEN RETURN; END IF;
  PERFORM net.http_post(url:=v_cfg.edge_url,
    headers:=jsonb_build_object('Content-Type','application/json','x-cron-secret',v_secret),
    body:=jsonb_build_object('origem','pg_cron','lote',v_cfg.lote),timeout_milliseconds:=55000);
END;
$fn$;
REVOKE ALL ON FUNCTION public.f2_sara_tick() FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.f2_sara_tick() TO service_role;

DO $do$ BEGIN
  IF EXISTS(SELECT 1 FROM pg_extension WHERE extname='pg_cron') THEN
    BEGIN PERFORM cron.unschedule('f2_sara_reclassificar'); EXCEPTION WHEN others THEN NULL; END;
    PERFORM cron.schedule('f2_sara_reclassificar','* * * * *',$$SELECT public.f2_sara_tick();$$);
  END IF;
END $do$;

COMMIT;
