-- Funil 2.0 — operação completa do laboratório isolado.
--
-- Amplia somente objetos f2_*: etapas e momentos configuráveis, Pipe de
-- Visitas, Esteira de Vendas e troca segura das duas cópias pelo Aquário.
-- Nenhuma tabela operacional é escrita.
BEGIN;

CREATE TABLE public.f2_etapa_config (
  codigo text PRIMARY KEY CHECK (codigo ~ '^[a-z0-9_]{3,40}$'),
  ordem smallint NOT NULL UNIQUE CHECK (ordem BETWEEN 1 AND 50),
  rotulo text NOT NULL CHECK (char_length(btrim(rotulo)) BETWEEN 2 AND 60),
  ajuda text NOT NULL DEFAULT '',
  ativo boolean NOT NULL DEFAULT true,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.f2_etapa_config(codigo,ordem,rotulo,ajuda) VALUES
  ('novo',1,'Novo','Chegou agora; primeira abordagem em até 5 minutos.'),
  ('tentando_contato',2,'Tentando contato','Nunca respondeu; seguir os dias 1, 2, 4, 6 e 7.'),
  ('em_atendimento',3,'Em atendimento','Respondeu; entender, avançar produto e produzir visita.'),
  ('pos_visita',4,'Pós-visita','Registrar feedback e transformar a visita em próximo avanço.')
ON CONFLICT (codigo) DO UPDATE SET
  ordem=EXCLUDED.ordem,rotulo=EXCLUDED.rotulo,ajuda=EXCLUDED.ajuda,ativo=true;

ALTER TABLE public.f2_momento_config DROP CONSTRAINT IF EXISTS f2_momento_config_etapa_check;
ALTER TABLE public.f2_momento_config DROP CONSTRAINT IF EXISTS f2_momento_config_ordem_check;
ALTER TABLE public.f2_momento_config DROP CONSTRAINT IF EXISTS f2_momento_config_ordem_key;
ALTER TABLE public.f2_lead DROP CONSTRAINT IF EXISTS f2_lead_etapa_check;
ALTER TABLE public.f2_momento_config
  ADD CONSTRAINT f2_momento_config_etapa_fkey FOREIGN KEY (etapa) REFERENCES public.f2_etapa_config(codigo);
ALTER TABLE public.f2_lead
  ADD CONSTRAINT f2_lead_etapa_fkey FOREIGN KEY (etapa) REFERENCES public.f2_etapa_config(codigo);
ALTER TABLE public.f2_momento_config
  ADD CONSTRAINT f2_momento_config_ordem_check CHECK (ordem BETWEEN 1 AND 100),
  ADD COLUMN IF NOT EXISTS criado_em timestamptz NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS atualizado_em timestamptz NOT NULL DEFAULT now();
CREATE UNIQUE INDEX IF NOT EXISTS f2_momento_etapa_ordem_uk ON public.f2_momento_config(etapa,ordem);

CREATE TABLE public.f2_visita (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  funil_lead_id uuid NOT NULL REFERENCES public.f2_lead(id) ON DELETE CASCADE,
  inicio_em timestamptz NOT NULL,
  imovel text NOT NULL CHECK (char_length(btrim(imovel)) BETWEEN 2 AND 120),
  status text NOT NULL DEFAULT 'agendada' CHECK (status IN ('agendada','confirmada','realizada','cancelada','nao_compareceu')),
  observacao text NULL CHECK (observacao IS NULL OR char_length(observacao)<=500),
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_por uuid NULL
);
CREATE INDEX f2_visita_status_inicio_idx ON public.f2_visita(status,inicio_em);

CREATE TABLE public.f2_negociacao (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  funil_lead_id uuid NOT NULL REFERENCES public.f2_lead(id) ON DELETE CASCADE,
  titulo text NOT NULL CHECK (char_length(btrim(titulo)) BETWEEN 2 AND 120),
  etapa text NOT NULL DEFAULT 'qualificacao' CHECK (etapa IN ('qualificacao','simulacao','proposta','documentacao','contrato','venda','perdida')),
  valor numeric(14,2) NULL CHECK (valor IS NULL OR valor>=0),
  observacao text NULL CHECK (observacao IS NULL OR char_length(observacao)<=500),
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_por uuid NULL
);
CREATE INDEX f2_negociacao_etapa_idx ON public.f2_negociacao(etapa,atualizado_em DESC);

CREATE TABLE public.f2_config_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo text NOT NULL CHECK (tipo IN ('etapa','momento','visita','negociacao','pesca')),
  chave text NOT NULL,
  acao text NOT NULL,
  antes jsonb NULL,
  depois jsonb NULL,
  criado_em timestamptz NOT NULL DEFAULT now(),
  criado_por uuid NULL
);

ALTER TABLE public.f2_etapa_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.f2_visita ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.f2_negociacao ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.f2_config_audit ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.f2_etapa_config,public.f2_visita,public.f2_negociacao,public.f2_config_audit FROM PUBLIC,anon;
GRANT SELECT ON public.f2_etapa_config,public.f2_visita,public.f2_negociacao,public.f2_config_audit TO authenticated;

CREATE POLICY f2_etapa_admin_select ON public.f2_etapa_config FOR SELECT TO authenticated USING (public.f2_admin());
CREATE POLICY f2_visita_admin_select ON public.f2_visita FOR SELECT TO authenticated USING (public.f2_admin());
CREATE POLICY f2_negociacao_admin_select ON public.f2_negociacao FOR SELECT TO authenticated USING (public.f2_admin());
CREATE POLICY f2_audit_admin_select ON public.f2_config_audit FOR SELECT TO authenticated USING (public.f2_admin());

CREATE OR REPLACE FUNCTION public.f2_configurar_etapa(
  p_codigo text,p_rotulo text,p_ajuda text,p_ordem integer,p_ativo boolean DEFAULT true
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO '' AS $fn$
DECLARE v_uid uuid:=(SELECT auth.uid()); v_antes jsonb; v_codigo text:=lower(btrim(p_codigo));
BEGIN
  IF v_uid IS NULL OR public.f2_admin() IS NOT TRUE THEN RETURN jsonb_build_object('ok',false,'erro','sem_permissao'); END IF;
  IF v_codigo !~ '^[a-z0-9_]{3,40}$' OR char_length(btrim(p_rotulo)) NOT BETWEEN 2 AND 60 OR p_ordem NOT BETWEEN 1 AND 50
    THEN RETURN jsonb_build_object('ok',false,'erro','dados_invalidos'); END IF;
  SELECT to_jsonb(e) INTO v_antes FROM public.f2_etapa_config e WHERE codigo=v_codigo;
  IF p_ativo IS FALSE AND (EXISTS(SELECT 1 FROM public.f2_lead WHERE etapa=v_codigo) OR EXISTS(SELECT 1 FROM public.f2_momento_config WHERE etapa=v_codigo AND ativo))
    THEN RETURN jsonb_build_object('ok',false,'erro','etapa_em_uso'); END IF;
  INSERT INTO public.f2_etapa_config(codigo,ordem,rotulo,ajuda,ativo,atualizado_em)
  VALUES(v_codigo,p_ordem,btrim(p_rotulo),left(COALESCE(p_ajuda,''),240),COALESCE(p_ativo,true),now())
  ON CONFLICT(codigo) DO UPDATE SET ordem=EXCLUDED.ordem,rotulo=EXCLUDED.rotulo,ajuda=EXCLUDED.ajuda,ativo=EXCLUDED.ativo,atualizado_em=now();
  INSERT INTO public.f2_config_audit(tipo,chave,acao,antes,depois,criado_por)
  SELECT 'etapa',v_codigo,CASE WHEN v_antes IS NULL THEN 'criar' ELSE 'atualizar' END,v_antes,to_jsonb(e),v_uid FROM public.f2_etapa_config e WHERE codigo=v_codigo;
  RETURN jsonb_build_object('ok',true,'codigo',v_codigo);
EXCEPTION WHEN unique_violation THEN RETURN jsonb_build_object('ok',false,'erro','ordem_em_uso');
END;$fn$;

CREATE OR REPLACE FUNCTION public.f2_configurar_momento(
  p_codigo text,p_etapa text,p_rotulo text,p_descricao text,p_acao_rotulo text,
  p_prazo_minutos integer,p_ordem integer,p_exige_dapi boolean DEFAULT false,p_ativo boolean DEFAULT true
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO '' AS $fn$
DECLARE v_uid uuid:=(SELECT auth.uid()); v_antes jsonb; v_codigo text:=upper(btrim(p_codigo));
BEGIN
  IF v_uid IS NULL OR public.f2_admin() IS NOT TRUE THEN RETURN jsonb_build_object('ok',false,'erro','sem_permissao'); END IF;
  IF v_codigo !~ '^[A-Z0-9_]{3,50}$' OR NOT EXISTS(SELECT 1 FROM public.f2_etapa_config WHERE codigo=p_etapa AND ativo)
     OR char_length(btrim(p_rotulo)) NOT BETWEEN 2 AND 80 OR char_length(btrim(p_acao_rotulo)) NOT BETWEEN 2 AND 120
     OR p_prazo_minutos NOT BETWEEN 1 AND 43200 OR p_ordem NOT BETWEEN 1 AND 100
    THEN RETURN jsonb_build_object('ok',false,'erro','dados_invalidos'); END IF;
  SELECT to_jsonb(m) INTO v_antes FROM public.f2_momento_config m WHERE codigo=v_codigo;
  IF p_ativo IS FALSE AND EXISTS(SELECT 1 FROM public.f2_lead WHERE momento_codigo=v_codigo)
    THEN RETURN jsonb_build_object('ok',false,'erro','momento_em_uso'); END IF;
  INSERT INTO public.f2_momento_config(codigo,etapa,ordem,rotulo,descricao,acao_codigo,acao_rotulo,prazo_minutos,prazo_rotulo,exige_dapi,ativo,atualizado_em)
  VALUES(v_codigo,p_etapa,p_ordem,btrim(p_rotulo),left(btrim(p_descricao),300),v_codigo,btrim(p_acao_rotulo),p_prazo_minutos,
    CASE WHEN p_prazo_minutos%1440=0 THEN (p_prazo_minutos/1440)||' dia(s)' WHEN p_prazo_minutos%60=0 THEN (p_prazo_minutos/60)||' hora(s)' ELSE p_prazo_minutos||' minutos' END,
    COALESCE(p_exige_dapi,false),COALESCE(p_ativo,true),now())
  ON CONFLICT(codigo) DO UPDATE SET etapa=EXCLUDED.etapa,ordem=EXCLUDED.ordem,rotulo=EXCLUDED.rotulo,
    descricao=EXCLUDED.descricao,acao_codigo=EXCLUDED.acao_codigo,acao_rotulo=EXCLUDED.acao_rotulo,
    prazo_minutos=EXCLUDED.prazo_minutos,prazo_rotulo=EXCLUDED.prazo_rotulo,exige_dapi=EXCLUDED.exige_dapi,ativo=EXCLUDED.ativo,atualizado_em=now();
  INSERT INTO public.f2_config_audit(tipo,chave,acao,antes,depois,criado_por)
  SELECT 'momento',v_codigo,CASE WHEN v_antes IS NULL THEN 'criar' ELSE 'atualizar' END,v_antes,to_jsonb(m),v_uid FROM public.f2_momento_config m WHERE codigo=v_codigo;
  RETURN jsonb_build_object('ok',true,'codigo',v_codigo);
EXCEPTION WHEN unique_violation THEN RETURN jsonb_build_object('ok',false,'erro','ordem_em_uso');
END;$fn$;

CREATE OR REPLACE FUNCTION public.f2_salvar_visita(
  p_id uuid,p_lead_id uuid,p_inicio_em timestamptz,p_imovel text,p_status text DEFAULT 'agendada',p_observacao text DEFAULT NULL
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO '' AS $fn$
DECLARE v_uid uuid:=(SELECT auth.uid()); v_id uuid:=COALESCE(p_id,gen_random_uuid());
BEGIN
  IF v_uid IS NULL OR public.f2_admin() IS NOT TRUE THEN RETURN jsonb_build_object('ok',false,'erro','sem_permissao'); END IF;
  IF NOT EXISTS(SELECT 1 FROM public.f2_lead WHERE id=p_lead_id) OR p_status NOT IN ('agendada','confirmada','realizada','cancelada','nao_compareceu')
    OR p_inicio_em IS NULL OR char_length(btrim(p_imovel)) NOT BETWEEN 2 AND 120 THEN RETURN jsonb_build_object('ok',false,'erro','dados_invalidos'); END IF;
  INSERT INTO public.f2_visita(id,funil_lead_id,inicio_em,imovel,status,observacao,atualizado_por)
  VALUES(v_id,p_lead_id,p_inicio_em,btrim(p_imovel),p_status,left(p_observacao,500),v_uid)
  ON CONFLICT(id) DO UPDATE SET inicio_em=EXCLUDED.inicio_em,imovel=EXCLUDED.imovel,status=EXCLUDED.status,observacao=EXCLUDED.observacao,atualizado_em=now(),atualizado_por=v_uid
  WHERE public.f2_visita.funil_lead_id=p_lead_id;
  INSERT INTO public.f2_config_audit(tipo,chave,acao,depois,criado_por) SELECT 'visita',v_id::text,'salvar',to_jsonb(v),v_uid FROM public.f2_visita v WHERE id=v_id;
  RETURN jsonb_build_object('ok',true,'id',v_id);
END;$fn$;

CREATE OR REPLACE FUNCTION public.f2_salvar_negociacao(
  p_id uuid,p_lead_id uuid,p_titulo text,p_etapa text DEFAULT 'qualificacao',p_valor numeric DEFAULT NULL,p_observacao text DEFAULT NULL
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO '' AS $fn$
DECLARE v_uid uuid:=(SELECT auth.uid()); v_id uuid:=COALESCE(p_id,gen_random_uuid());
BEGIN
  IF v_uid IS NULL OR public.f2_admin() IS NOT TRUE THEN RETURN jsonb_build_object('ok',false,'erro','sem_permissao'); END IF;
  IF NOT EXISTS(SELECT 1 FROM public.f2_lead WHERE id=p_lead_id) OR p_etapa NOT IN ('qualificacao','simulacao','proposta','documentacao','contrato','venda','perdida')
    OR char_length(btrim(p_titulo)) NOT BETWEEN 2 AND 120 OR (p_valor IS NOT NULL AND p_valor<0) THEN RETURN jsonb_build_object('ok',false,'erro','dados_invalidos'); END IF;
  INSERT INTO public.f2_negociacao(id,funil_lead_id,titulo,etapa,valor,observacao,atualizado_por)
  VALUES(v_id,p_lead_id,btrim(p_titulo),p_etapa,p_valor,left(p_observacao,500),v_uid)
  ON CONFLICT(id) DO UPDATE SET titulo=EXCLUDED.titulo,etapa=EXCLUDED.etapa,valor=EXCLUDED.valor,observacao=EXCLUDED.observacao,atualizado_em=now(),atualizado_por=v_uid
  WHERE public.f2_negociacao.funil_lead_id=p_lead_id;
  INSERT INTO public.f2_config_audit(tipo,chave,acao,depois,criado_por) SELECT 'negociacao',v_id::text,'salvar',to_jsonb(n),v_uid FROM public.f2_negociacao n WHERE id=v_id;
  RETURN jsonb_build_object('ok',true,'id',v_id);
END;$fn$;

CREATE OR REPLACE FUNCTION public.f2_listar_aquario()
RETURNS TABLE(negocio_id bigint,nome text,corretor_nome text,momento text)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO '' AS $fn$
  SELECT n.id,l.nome,c.nome,e.momento_codigo
  FROM public.ncrm_estado e
  JOIN public.negocios n ON n.id=e.negocio_id
  JOIN public.leads l ON l.id=n.lead_id
  LEFT JOIN public.corretores c ON c.id=n.corretor_id
  WHERE public.f2_admin() AND NOT EXISTS(SELECT 1 FROM public.f2_lead f WHERE f.origem_negocio_id=n.id)
  ORDER BY e.ultima_interacao_em DESC NULLS LAST,n.id DESC LIMIT 20;
$fn$;

CREATE OR REPLACE FUNCTION public.f2_pescar_negocio(p_negocio_id bigint,p_substituir_id uuid DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO '' AS $fn$
DECLARE v_uid uuid:=(SELECT auth.uid()); v_novo uuid;
BEGIN
  IF v_uid IS NULL OR public.f2_admin() IS NOT TRUE THEN RETURN jsonb_build_object('ok',false,'erro','sem_permissao'); END IF;
  IF EXISTS(SELECT 1 FROM public.f2_lead WHERE origem_negocio_id=p_negocio_id) THEN RETURN jsonb_build_object('ok',false,'erro','ja_esta_no_funil'); END IF;
  IF (SELECT count(*) FROM public.f2_lead)>=2 AND p_substituir_id IS NULL THEN RETURN jsonb_build_object('ok',false,'erro','escolha_copia_para_substituir'); END IF;
  IF p_substituir_id IS NOT NULL THEN
    IF NOT EXISTS(SELECT 1 FROM public.f2_lead WHERE id=p_substituir_id) THEN RETURN jsonb_build_object('ok',false,'erro','copia_invalida'); END IF;
    DELETE FROM public.f2_lead WHERE id=p_substituir_id;
  END IF;
  v_novo:=public.f2_importar_negocio(p_negocio_id);
  INSERT INTO public.f2_config_audit(tipo,chave,acao,depois,criado_por) VALUES('pesca',p_negocio_id::text,'substituir_copia',jsonb_build_object('novo_id',v_novo,'substituido',p_substituir_id),v_uid);
  RETURN jsonb_build_object('ok',true,'id',v_novo);
EXCEPTION WHEN OTHERS THEN RAISE;
END;$fn$;

REVOKE ALL ON FUNCTION public.f2_configurar_etapa(text,text,text,integer,boolean) FROM PUBLIC,anon;
REVOKE ALL ON FUNCTION public.f2_configurar_momento(text,text,text,text,text,integer,integer,boolean,boolean) FROM PUBLIC,anon;
REVOKE ALL ON FUNCTION public.f2_salvar_visita(uuid,uuid,timestamptz,text,text,text) FROM PUBLIC,anon;
REVOKE ALL ON FUNCTION public.f2_salvar_negociacao(uuid,uuid,text,text,numeric,text) FROM PUBLIC,anon;
REVOKE ALL ON FUNCTION public.f2_listar_aquario() FROM PUBLIC,anon;
REVOKE ALL ON FUNCTION public.f2_pescar_negocio(bigint,uuid) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.f2_configurar_etapa(text,text,text,integer,boolean) TO authenticated,service_role;
GRANT EXECUTE ON FUNCTION public.f2_configurar_momento(text,text,text,text,text,integer,integer,boolean,boolean) TO authenticated,service_role;
GRANT EXECUTE ON FUNCTION public.f2_salvar_visita(uuid,uuid,timestamptz,text,text,text) TO authenticated,service_role;
GRANT EXECUTE ON FUNCTION public.f2_salvar_negociacao(uuid,uuid,text,text,numeric,text) TO authenticated,service_role;
GRANT EXECUTE ON FUNCTION public.f2_listar_aquario() TO authenticated,service_role;
GRANT EXECUTE ON FUNCTION public.f2_pescar_negocio(bigint,uuid) TO authenticated,service_role;

COMMIT;
