-- CRM Nova Era 3.1 — etapa != momento, roleta operacional e feedback de visita.
--
-- Decisões da operação (03/08/2026):
--   * quatro ETAPAS do funil: Novo, Tentando contato, Em atendimento, Pós-visita;
--   * dez MOMENTOS padronizados, cada um com uma ação e um prazo;
--   * fora do horário não existe aceite/rejeição: o lead continua atribuído;
--   * redistribuição dos 5 minutos só ocorre no horário oficial;
--   * D-API conectada, presença e feedback de visita são critérios objetivos;
--   * suspensão por produtividade nasce DORMENTE até existir base de medição.
--
-- Esta migration não envia WhatsApp, não cria proposta/venda e não migra carteira.
BEGIN;

-- Backup lógico mínimo para rollback: definições exatas das funções alteradas,
-- catálogos ativos e horários anteriores. Somente service_role pode ler.
CREATE TABLE IF NOT EXISTS public.ncrm_operacao_v4_backup(
  chave text PRIMARY KEY,payload jsonb NOT NULL,criado_em timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.ncrm_operacao_v4_backup ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.ncrm_operacao_v4_backup FROM PUBLIC,anon,authenticated;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.ncrm_operacao_v4_backup TO service_role;
INSERT INTO public.ncrm_operacao_v4_backup(chave,payload) VALUES
 ('momentos_ativos',(SELECT coalesce(jsonb_agg(codigo),'[]') FROM public.ncrm_momento_padrao WHERE ativo)),
 ('acoes_ativas',(SELECT coalesce(jsonb_agg(codigo),'[]') FROM public.ncrm_acao_padrao WHERE ativa)),
 ('horarios',jsonb_build_object(
   'distribuicao',(SELECT to_jsonb(d) FROM public.distribuicao_config d WHERE id=1),
   'presenca',(SELECT to_jsonb(p) FROM public.presenca_config p WHERE id=1),
   'sla',(SELECT to_jsonb(s) FROM public.ncrm_sla_redistribuicao_config s WHERE id=true)))
ON CONFLICT(chave) DO NOTHING;

INSERT INTO public.ncrm_operacao_v4_backup(chave,payload)
SELECT 'funcao:'||x.assinatura,jsonb_build_object('definicao',pg_get_functiondef(p.oid),'md5',md5(pg_get_functiondef(p.oid)))
FROM unnest(ARRAY[
  'public.motor_roleta(bigint,text,text,jsonb,bigint,bigint,jsonb,boolean,boolean,jsonb)',
  'ncrm_private.sla_redistribuir(integer)',
  'public.aquario_pescar()',
  'public.pescar_lead_aquario(bigint)',
  'public.corretor_pode_receber(bigint)',
  'public.ncrm_agendar_visita_e_encaminhar(bigint,integer,bigint,date,text,uuid,text,boolean,bigint,text)',
  'public.ncrm_registrar_resultado_visita(uuid,bigint,integer,text,text,text)',
  'public.ncrm_sara_aplicar_proxima_acao(bigint,bigint,text)'
]) x(assinatura)
JOIN pg_proc p ON p.oid=to_regprocedure(x.assinatura)
ON CONFLICT(chave) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 1. Configuração operacional versionável (um único registro ativo)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ncrm_operacao_config (
  id boolean PRIMARY KEY DEFAULT true CHECK (id),
  timezone text NOT NULL DEFAULT 'America/Sao_Paulo',
  horario_oficial_inicio time NOT NULL DEFAULT '09:30',
  horario_oficial_fim time NOT NULL DEFAULT '18:30',
  presenca_ttl_min integer NOT NULL DEFAULT 15 CHECK (presenca_ttl_min BETWEEN 5 AND 120),
  primeira_abordagem_min integer NOT NULL DEFAULT 5 CHECK (primeira_abordagem_min BETWEEN 1 AND 30),
  feedback_visita_min integer NOT NULL DEFAULT 120 CHECK (feedback_visita_min BETWEEN 30 AND 1440),
  corte_feedback_visita timestamptz NOT NULL DEFAULT now(),
  sara_organiza_ativa boolean NOT NULL DEFAULT true,
  suspensao_automatica_ativa boolean NOT NULL DEFAULT false,
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_por uuid NULL
);
INSERT INTO public.ncrm_operacao_config(id) VALUES (true) ON CONFLICT (id) DO NOTHING;
ALTER TABLE public.ncrm_operacao_config ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.ncrm_operacao_config FROM PUBLIC, anon;
GRANT SELECT ON public.ncrm_operacao_config TO authenticated;
DROP POLICY IF EXISTS ncrm_operacao_config_leitura ON public.ncrm_operacao_config;
CREATE POLICY ncrm_operacao_config_leitura ON public.ncrm_operacao_config
  FOR SELECT TO authenticated USING (true);

-- Suspensão progressiva, auditável. Nada é criado automaticamente nesta rodada.
CREATE TABLE IF NOT EXISTS public.ncrm_corretor_suspensao (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  corretor_id bigint NOT NULL REFERENCES public.corretores(id) ON DELETE CASCADE,
  inicio_em timestamptz NOT NULL,
  fim_em timestamptz NOT NULL CHECK (fim_em > inicio_em),
  nivel smallint NOT NULL CHECK (nivel BETWEEN 1 AND 30),
  motivo text NOT NULL CHECK (char_length(btrim(motivo)) BETWEEN 3 AND 500),
  origem text NOT NULL DEFAULT 'gestao' CHECK (origem IN ('gestao','regra_automatica')),
  criado_em timestamptz NOT NULL DEFAULT now(),
  criado_por uuid NULL,
  revogada_em timestamptz NULL,
  revogada_por uuid NULL,
  revogacao_motivo text NULL
);
CREATE INDEX IF NOT EXISTS ncrm_corretor_suspensao_ativa_idx
  ON public.ncrm_corretor_suspensao(corretor_id,fim_em)
  WHERE revogada_em IS NULL;
ALTER TABLE public.ncrm_corretor_suspensao ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.ncrm_corretor_suspensao FROM PUBLIC, anon, authenticated;
GRANT SELECT,INSERT,UPDATE ON public.ncrm_corretor_suspensao TO service_role;

-- ---------------------------------------------------------------------------
-- 2. Dez momentos dentro das quatro etapas
-- ---------------------------------------------------------------------------
ALTER TABLE public.ncrm_momento_padrao DROP CONSTRAINT IF EXISTS ncrm_momento_padrao_etapa_key;
ALTER TABLE public.ncrm_momento_padrao DROP CONSTRAINT IF EXISTS ncrm_momento_padrao_ordem_key;
ALTER TABLE public.ncrm_momento_padrao DROP CONSTRAINT IF EXISTS ncrm_momento_padrao_ordem_check;
ALTER TABLE public.ncrm_momento_padrao
  ADD COLUMN IF NOT EXISTS acao_codigo text NULL,
  ADD COLUMN IF NOT EXISTS sla_min integer NULL,
  ADD COLUMN IF NOT EXISTS ajuda text NULL;

UPDATE public.ncrm_momento_padrao SET ativo=false;
INSERT INTO public.ncrm_momento_padrao
  (codigo,etapa,rotulo,objetivo,ordem,ativo,acao_codigo,sla_min,ajuda)
VALUES
 ('PRIMEIRA_ABORDAGEM','novo','Primeira abordagem','Iniciar a conversa enquanto o interesse está fresco.',1,true,'PRIMEIRA_ABORDAGEM',5,'No horário oficial, chame em até 5 minutos. Fora dele, o lead fica disponível sem aceite nem punição noturna.'),
 ('CADENCIA_SEM_RESPOSTA','tentando_contato','Cadência sem resposta','Produzir a primeira resposta sem abandonar o lead.',2,true,'ENVIAR_CADENCIA',360,'Siga os contatos dos dias 1, 2, 4, 6 e 7.'),
 ('CONVERSANDO_QUALIFICANDO','em_atendimento','Conversando e qualificando','Entender o perfil e manter a conversa viva.',3,true,'RESPONDER_E_QUALIFICAR',1440,'Responda perguntas e descubra região, produto, valor e prazo.'),
 ('BUSCANDO_PRODUTO','em_atendimento','Buscando produto','Encontrar opções compatíveis com o pedido do cliente.',4,true,'BUSCAR_E_ENVIAR_IMOVEIS',1440,'Procure e envie opções em até 24 horas.'),
 ('PRODUTO_ENVIADO','em_atendimento','Produto enviado','Transformar opções enviadas em resposta e preferência.',5,true,'PEDIR_RETORNO_PRODUTO',1440,'Peça retorno sobre as opções em até 24 horas.'),
 ('TENTANDO_AGENDAMENTO','em_atendimento','Tentando agendamento','Converter interesse em uma visita com data e hora.',6,true,'AGENDAR_VISITA',720,'Não deixe passar mais de 12 horas sem avançar o agendamento.'),
 ('VISITA_AGENDADA','em_atendimento','Visita agendada','Garantir presença e preparo para a visita.',7,true,'CONFIRMAR_VISITA',1440,'Confirme a visita 24 horas antes do horário marcado.'),
 ('RETORNO_PROGRAMADO','em_atendimento','Retorno programado','Retomar exatamente no combinado com o cliente.',8,true,'RETOMAR_NO_COMBINADO',7200,'Use data e hora exatas; sem data, o limite é 5 dias.'),
 ('FEEDBACK_POS_VISITA','em_acompanhamento','Feedback pós-visita','Registrar o que aconteceu e definir o desfecho.',9,true,'REGISTRAR_RESULTADO_VISITA',120,'Registre o resultado em até 2 horas após a visita.'),
 ('DECISAO_POS_VISITA','em_acompanhamento','Decisão pós-visita','Transformar a visita em próximo avanço, nova opção ou proposta.',10,true,'AVANCAR_POS_VISITA',1440,'Atualize a decisão e o próximo passo em até 24 horas.')
ON CONFLICT (codigo) DO UPDATE SET
 etapa=EXCLUDED.etapa,rotulo=EXCLUDED.rotulo,objetivo=EXCLUDED.objetivo,
 ordem=EXCLUDED.ordem,ativo=true,acao_codigo=EXCLUDED.acao_codigo,
 sla_min=EXCLUDED.sla_min,ajuda=EXCLUDED.ajuda;

CREATE UNIQUE INDEX IF NOT EXISTS ncrm_momento_padrao_ordem_ativa_idx
  ON public.ncrm_momento_padrao(ordem) WHERE ativo;

ALTER TABLE public.ncrm_estado ADD COLUMN IF NOT EXISTS momento_codigo text NULL;
CREATE INDEX IF NOT EXISTS ncrm_estado_momento_acao_idx
  ON public.ncrm_estado(momento_codigo,proxima_acao_em)
  WHERE saida IS NULL;

-- Backfill conservador: usa apenas fatos já estruturados. Não inventa contexto.
UPDATE public.ncrm_estado e SET momento_codigo = CASE
  WHEN e.etapa='novo' THEN 'PRIMEIRA_ABORDAGEM'
  WHEN e.etapa='tentando_contato' THEN 'CADENCIA_SEM_RESPOSTA'
  WHEN e.etapa='em_acompanhamento' AND e.visita_id IS NOT NULL THEN 'FEEDBACK_POS_VISITA'
  WHEN e.etapa='em_acompanhamento' THEN 'DECISAO_POS_VISITA'
  WHEN e.visita_id IS NOT NULL THEN 'VISITA_AGENDADA'
  WHEN lower(coalesce(e.proxima_acao_tipo,''))='agendar_visita' THEN 'TENTANDO_AGENDAMENTO'
  WHEN lower(coalesce(e.proxima_acao_tipo,''))='enviar_opcoes' THEN 'BUSCANDO_PRODUTO'
  WHEN lower(coalesce(e.proxima_acao_tipo,''))='confirmar_recebimento' THEN 'PRODUTO_ENVIADO'
  WHEN lower(coalesce(e.proxima_acao_titulo,'')) ~ '(retorno|combinado|viagem)' THEN 'RETORNO_PROGRAMADO'
  ELSE 'CONVERSANDO_QUALIFICANDO' END
WHERE e.momento_codigo IS NULL;

-- Catálogo fechado de dez ações. Proposta e visita seguem CTAs próprios.
UPDATE public.ncrm_acao_padrao SET ativa=false;
INSERT INTO public.ncrm_acao_padrao(codigo,rotulo,proxima_acao_tipo,sla_min,ordem,objetivo,ativa) VALUES
 ('PRIMEIRA_ABORDAGEM','Fazer a primeira abordagem','tentativa_cadencia',5,10,'No horário oficial, iniciar em até 5 minutos; fora dele, chamar agora ou no próximo período.',true),
 ('ENVIAR_CADENCIA','Enviar a mensagem da cadência','tentativa_cadencia',360,20,'Conseguir a primeira resposta sem deixar o lead parar.',true),
 ('RESPONDER_E_QUALIFICAR','Responder e qualificar','entender_necessidade',1440,30,'Manter a conversa viva e completar o perfil.',true),
 ('BUSCAR_E_ENVIAR_IMOVEIS','Buscar e enviar imóveis','enviar_opcoes',1440,40,'Entregar opções compatíveis em até 24 horas.',true),
 ('PEDIR_RETORNO_PRODUTO','Pedir retorno sobre as opções','confirmar_recebimento',1440,50,'Descobrir o que agradou e ajustar a busca.',true),
 ('AGENDAR_VISITA','Agendar uma visita','agendar_visita',720,60,'Transformar interesse em visita com data e hora.',true),
 ('CONFIRMAR_VISITA','Confirmar a visita','agendar_visita',1440,70,'Confirmar presença 24 horas antes da visita.',true),
 ('RETOMAR_NO_COMBINADO','Retomar no horário combinado','retornar_contato',7200,80,'Retomar na data e hora combinadas, no máximo em 5 dias.',true),
 ('REGISTRAR_RESULTADO_VISITA','Registrar o resultado da visita','retornar_contato',120,90,'Registrar o desfecho em até 2 horas.',true),
 ('AVANCAR_POS_VISITA','Definir o avanço pós-visita','retornar_contato',1440,100,'Definir nova opção, retorno ou proposta em até 24 horas.',true)
ON CONFLICT (codigo) DO UPDATE SET rotulo=EXCLUDED.rotulo,
 proxima_acao_tipo=EXCLUDED.proxima_acao_tipo,sla_min=EXCLUDED.sla_min,
 ordem=EXCLUDED.ordem,objetivo=EXCLUDED.objetivo,ativa=true;

-- Regra central: estágio e momento determinam uma única conduta.
CREATE OR REPLACE FUNCTION public.ncrm_conduta_oficial_v4(
  p_etapa text,p_momento_codigo text,p_respondeu boolean,p_resposta_pendente boolean,
  p_tentativas integer,p_proxima_em timestamptz
) RETURNS jsonb LANGUAGE sql STABLE SET search_path='' AS $fn$
  WITH escolhido AS (
    SELECT m.* FROM public.ncrm_momento_padrao m
    WHERE m.ativo AND m.codigo = CASE
      WHEN p_etapa='novo' THEN 'PRIMEIRA_ABORDAGEM'
      WHEN p_etapa='tentando_contato' AND NOT coalesce(p_respondeu,false) THEN 'CADENCIA_SEM_RESPOSTA'
      WHEN p_momento_codigo IS NOT NULL THEN p_momento_codigo
      WHEN p_etapa='em_acompanhamento' THEN 'DECISAO_POS_VISITA'
      ELSE 'CONVERSANDO_QUALIFICANDO' END
    LIMIT 1
  )
  SELECT jsonb_build_object(
    'etapa',e.etapa,'momento_codigo',e.codigo,'momento',e.rotulo,'momento_ordem',e.ordem,
    'acao_codigo',CASE WHEN coalesce(p_resposta_pendente,false) THEN 'RESPONDER_E_QUALIFICAR' ELSE e.acao_codigo END,
    'acao',CASE
      WHEN e.codigo='CADENCIA_SEM_RESPOSTA' THEN concat('Enviar cadência ',LEAST(GREATEST(coalesce(p_tentativas,0)+1,1),5),' de 5')
      WHEN coalesce(p_resposta_pendente,false) THEN 'Responder e qualificar'
      ELSE a.rotulo END,
    'objetivo',CASE WHEN coalesce(p_resposta_pendente,false) THEN 'Responder o cliente e manter a conversa avançando.' ELSE a.objetivo END,
    'prazo',p_proxima_em,'sla_min',CASE WHEN coalesce(p_resposta_pendente,false) THEN 15 ELSE e.sla_min END,
    'ajuda',e.ajuda
  )
  FROM escolhido e
  JOIN public.ncrm_acao_padrao a ON a.codigo=CASE WHEN coalesce(p_resposta_pendente,false) THEN 'RESPONDER_E_QUALIFICAR' ELSE e.acao_codigo END;
$fn$;
REVOKE ALL ON FUNCTION public.ncrm_conduta_oficial_v4(text,text,boolean,boolean,integer,timestamptz)
  FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.ncrm_conduta_oficial_v4(text,text,boolean,boolean,integer,timestamptz)
  TO service_role;

-- Atualização manual por menu suspenso. Etapa é derivada do momento escolhido.
CREATE OR REPLACE FUNCTION public.ncrm_atualizar_momento(
  p_negocio_id bigint,p_versao integer,p_momento_codigo text,p_observacao text DEFAULT NULL
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $fn$
DECLARE v_uid uuid:=auth.uid(); v_m public.ncrm_momento_padrao%ROWTYPE;
        v_e public.ncrm_estado%ROWTYPE; v_lead bigint; v_corretor bigint; v_prazo timestamptz;
BEGIN
  IF v_uid IS NULL THEN RETURN jsonb_build_object('ok',false,'erro','nao_autenticado'); END IF;
  IF ncrm_private.pode_operar_negocio(p_negocio_id) IS NOT TRUE THEN
    RETURN jsonb_build_object('ok',false,'erro','sem_permissao'); END IF;
  SELECT * INTO v_m FROM public.ncrm_momento_padrao WHERE codigo=p_momento_codigo AND ativo;
  IF v_m.codigo IS NULL THEN RETURN jsonb_build_object('ok',false,'erro','momento_invalido'); END IF;
  SELECT * INTO v_e FROM public.ncrm_estado WHERE negocio_id=p_negocio_id FOR UPDATE;
  IF v_e.negocio_id IS NULL THEN RETURN jsonb_build_object('ok',false,'erro','estado_inexistente'); END IF;
  IF v_e.saida IS NOT NULL THEN RETURN jsonb_build_object('ok',false,'erro','estado_em_saida'); END IF;
  IF v_e.versao<>p_versao THEN RETURN jsonb_build_object('ok',false,'erro','versao_conflito'); END IF;
  SELECT lead_id,corretor_id INTO v_lead,v_corretor FROM public.negocios WHERE id=p_negocio_id;
  v_prazo:=now()+make_interval(mins=>v_m.sla_min);
  UPDATE public.ncrm_estado SET etapa=v_m.etapa,momento_codigo=v_m.codigo,
    proxima_acao_tipo=(SELECT proxima_acao_tipo FROM public.ncrm_acao_padrao WHERE codigo=v_m.acao_codigo),
    proxima_acao_titulo=(SELECT rotulo FROM public.ncrm_acao_padrao WHERE codigo=v_m.acao_codigo),
    proxima_acao_em=v_prazo,proxima_acao_motivo=coalesce(nullif(btrim(p_observacao),''),v_m.objetivo),
    proxima_acao_origem='corretor',versao=v_e.versao+1,atualizado_em=now(),atualizado_por=v_uid,
    origem_ultima='usuario',ultima_decisao_humana_em=now()
  WHERE negocio_id=p_negocio_id AND versao=v_e.versao;
  INSERT INTO public.ncrm_evento(negocio_id,lead_id,corretor_id_no_evento,workflow_config_id,
    tipo,resultado,payload,origem,executado_por,idempotency_key,estado_versao_antes,estado_versao_apos)
  VALUES(p_negocio_id,v_lead,v_corretor,v_e.workflow_config_id,'correcao_manual',v_m.codigo,
    jsonb_build_object('etapa_anterior',v_e.etapa,'momento_anterior',v_e.momento_codigo,'observacao',p_observacao),
    'usuario',v_uid,concat('momento:',p_negocio_id,':',v_e.versao+1),v_e.versao,v_e.versao+1);
  RETURN jsonb_build_object('ok',true,'etapa',v_m.etapa,'momento_codigo',v_m.codigo,
    'momento',v_m.rotulo,'acao_codigo',v_m.acao_codigo,'prazo',v_prazo,'versao',v_e.versao+1);
END $fn$;
REVOKE ALL ON FUNCTION public.ncrm_atualizar_momento(bigint,integer,text,text) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.ncrm_atualizar_momento(bigint,integer,text,text) TO authenticated;

-- ---------------------------------------------------------------------------
-- 2.1. Uma visita é um evento paralelo, não uma saída do funil de atendimento
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.ncrm_agendar_visita_e_encaminhar(
  p_negocio_id bigint,p_versao integer,p_lead_id bigint,p_data date,p_hora_inicio text,
  p_empreendimento_id uuid,p_produto text,p_com_gerente boolean,p_gerente_id bigint,p_idem text
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $fn$
DECLARE v_uid uuid:=auth.uid(); v_lead bigint; v_corretor bigint; v_antes int; v_cfg bigint;
        v_nome text; v_visita uuid; v_inicio timestamptz; v_prazo timestamptz;
BEGIN
  PERFORM ncrm_private.assert_idem(p_idem);
  IF v_uid IS NULL THEN RETURN jsonb_build_object('ok',false,'erro','nao_autenticado'); END IF;
  SELECT n.lead_id,n.corretor_id INTO v_lead,v_corretor FROM public.negocios n WHERE n.id=p_negocio_id;
  IF NOT FOUND THEN RETURN jsonb_build_object('ok',false,'erro','negocio_inexistente'); END IF;
  IF ncrm_private.pode_operar_negocio(p_negocio_id) IS NOT TRUE THEN RETURN jsonb_build_object('ok',false,'erro','sem_permissao'); END IF;
  IF p_lead_id IS NULL OR p_lead_id<>v_lead THEN RETURN jsonb_build_object('ok',false,'erro','lead_incoerente'); END IF;
  IF p_data IS NULL OR p_hora_inicio IS NULL OR btrim(p_hora_inicio)='' THEN RETURN jsonb_build_object('ok',false,'erro','data_hora_obrigatorias'); END IF;
  v_inicio:=(p_data+p_hora_inicio::time) AT TIME ZONE 'America/Sao_Paulo';
  IF v_inicio<now() THEN RETURN jsonb_build_object('ok',false,'erro','data_no_passado'); END IF;
  IF EXISTS(SELECT 1 FROM public.ncrm_evento WHERE idempotency_key=p_idem) THEN RETURN jsonb_build_object('ok',true,'ja_processado',true); END IF;
  SELECT versao,workflow_config_id INTO v_antes,v_cfg FROM public.ncrm_estado WHERE negocio_id=p_negocio_id AND saida IS NULL FOR UPDATE;
  IF NOT FOUND THEN RETURN jsonb_build_object('ok',false,'erro','estado_indisponivel'); END IF;
  IF p_versao<>v_antes THEN RETURN jsonb_build_object('ok',false,'erro','versao_conflito'); END IF;
  SELECT nome INTO v_nome FROM public.leads WHERE id=v_lead;
  INSERT INTO public.visitas(created_by,lead_id,negocio_id,corretor_id,cliente_nome,empreendimento_id,produto,
    data,hora_inicio,com_gerente,gerente_id,status)
  VALUES(v_uid,v_lead,p_negocio_id,v_corretor,v_nome,p_empreendimento_id,p_produto,p_data,p_hora_inicio,
    coalesce(p_com_gerente,false),p_gerente_id,'agendada') RETURNING id INTO v_visita;
  v_prazo:=greatest(now()+interval '1 minute',v_inicio-interval '24 hours');
  UPDATE public.ncrm_estado SET etapa='em_atendimento',momento_codigo='VISITA_AGENDADA',
    saida=NULL,saida_em=NULL,visita_id=v_visita,proxima_acao_tipo='agendar_visita',
    proxima_acao_titulo='Confirmar a visita',proxima_acao_em=v_prazo,
    proxima_acao_motivo='confirmar presença 24 horas antes',proxima_acao_origem='visita',
    resposta_pendente=false,versao=v_antes+1,atualizado_em=now(),atualizado_por=v_uid,
    origem_ultima='usuario',ultima_decisao_humana_em=now()
  WHERE negocio_id=p_negocio_id AND versao=v_antes;
  INSERT INTO public.ncrm_evento(negocio_id,lead_id,corretor_id_no_evento,workflow_config_id,tipo,payload,
    origem,executado_por,idempotency_key,estado_versao_antes,estado_versao_apos)
  VALUES(p_negocio_id,v_lead,v_corretor,v_cfg,'visita_agendada',
    jsonb_build_object('visita_id',v_visita,'data',p_data,'hora',p_hora_inicio,'mesmo_atendimento',true),
    'usuario',v_uid,p_idem,v_antes,v_antes+1);
  RETURN jsonb_build_object('ok',true,'versao',v_antes+1,'visita_id',v_visita,
    'etapa','em_atendimento','momento_codigo','VISITA_AGENDADA');
EXCEPTION WHEN unique_violation THEN
  IF EXISTS(SELECT 1 FROM public.ncrm_evento WHERE idempotency_key=p_idem) THEN
    RETURN jsonb_build_object('ok',true,'ja_processado',true); ELSE RAISE; END IF;
END $fn$;

CREATE OR REPLACE FUNCTION public.ncrm_registrar_resultado_visita(
  p_visita_id uuid,p_negocio_id bigint,p_versao integer,p_resultado text,p_obs text,p_idem text
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $fn$
DECLARE v_uid uuid:=auth.uid(); v_lead bigint; v_corretor bigint; v_antes int; v_cfg bigint;
        v_etapa text; v_momento text; v_tipo text; v_titulo text; v_prazo timestamptz;
BEGIN
  PERFORM ncrm_private.assert_idem(p_idem);
  IF v_uid IS NULL THEN RETURN jsonb_build_object('ok',false,'erro','nao_autenticado'); END IF;
  IF p_resultado NOT IN('interessado','quer_outra_opcao','precisa_conversar','nao_gostou','nao_compareceu','remarcar','fara_proposta') THEN
    RETURN jsonb_build_object('ok',false,'erro','resultado_invalido'); END IF;
  SELECT n.lead_id,n.corretor_id INTO v_lead,v_corretor FROM public.negocios n WHERE n.id=p_negocio_id;
  IF NOT FOUND OR ncrm_private.pode_operar_negocio(p_negocio_id) IS NOT TRUE THEN RETURN jsonb_build_object('ok',false,'erro','sem_permissao'); END IF;
  IF NOT EXISTS(SELECT 1 FROM public.visitas WHERE id=p_visita_id AND negocio_id=p_negocio_id) THEN RETURN jsonb_build_object('ok',false,'erro','visita_invalida'); END IF;
  IF EXISTS(SELECT 1 FROM public.ncrm_evento WHERE idempotency_key=p_idem) THEN RETURN jsonb_build_object('ok',true,'ja_processado',true); END IF;
  SELECT versao,workflow_config_id INTO v_antes,v_cfg FROM public.ncrm_estado WHERE negocio_id=p_negocio_id AND saida IS NULL FOR UPDATE;
  IF NOT FOUND THEN RETURN jsonb_build_object('ok',false,'erro','estado_indisponivel'); END IF;
  IF p_versao<>v_antes THEN RETURN jsonb_build_object('ok',false,'erro','versao_conflito'); END IF;

  IF p_resultado IN('nao_compareceu','remarcar') THEN
    v_etapa:='em_atendimento'; v_momento:='TENTANDO_AGENDAMENTO'; v_tipo:='agendar_visita';
    v_titulo:='Agendar uma visita'; v_prazo:=now()+interval '12 hours';
  ELSIF p_resultado IN('quer_outra_opcao','nao_gostou') THEN
    v_etapa:='em_atendimento'; v_momento:='BUSCANDO_PRODUTO'; v_tipo:='enviar_opcoes';
    v_titulo:='Buscar e enviar imóveis'; v_prazo:=now()+interval '24 hours';
  ELSE
    v_etapa:='em_acompanhamento'; v_momento:='DECISAO_POS_VISITA'; v_tipo:='retornar_contato';
    v_titulo:='Definir o avanço pós-visita'; v_prazo:=now()+interval '24 hours';
  END IF;

  UPDATE public.visitas SET resultado=p_resultado,resultado_em=now(),resultado_por=v_uid,
    status=CASE WHEN p_resultado='nao_compareceu' THEN 'nao_compareceu' ELSE 'realizada' END
  WHERE id=p_visita_id;
  UPDATE public.ncrm_estado SET etapa=v_etapa,momento_codigo=v_momento,saida=NULL,saida_em=NULL,
    respondeu=true,resposta_pendente=false,proxima_acao_tipo=v_tipo,proxima_acao_titulo=v_titulo,
    proxima_acao_em=v_prazo,proxima_acao_motivo='resultado da visita: '||p_resultado,
    proxima_acao_origem='visita',ultima_interacao_em=now(),versao=v_antes+1,atualizado_em=now(),
    atualizado_por=v_uid,origem_ultima='usuario',ultima_decisao_humana_em=now()
  WHERE negocio_id=p_negocio_id AND versao=v_antes;
  INSERT INTO public.ncrm_evento(negocio_id,lead_id,corretor_id_no_evento,workflow_config_id,tipo,
    resultado,payload,origem,executado_por,idempotency_key,estado_versao_antes,estado_versao_apos)
  VALUES(p_negocio_id,v_lead,v_corretor,v_cfg,'acao_comercial',p_resultado,
    jsonb_build_object('visita_id',p_visita_id,'obs',p_obs,'origem','resultado_visita','momento_codigo',v_momento),
    'usuario',v_uid,p_idem,v_antes,v_antes+1);
  RETURN jsonb_build_object('ok',true,'versao',v_antes+1,'etapa',v_etapa,
    'momento_codigo',v_momento,'proxima_acao',v_titulo);
EXCEPTION WHEN unique_violation THEN
  IF EXISTS(SELECT 1 FROM public.ncrm_evento WHERE idempotency_key=p_idem) THEN
    RETURN jsonb_build_object('ok',true,'ja_processado',true); ELSE RAISE; END IF;
END $fn$;

-- ---------------------------------------------------------------------------
-- 3. Elegibilidade da roleta: presença + D-API + visitas + suspensão
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.ncrm_corretor_elegibilidade(
  p_corretor_id bigint,p_agora timestamptz DEFAULT now()
) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path='' AS $fn$
DECLARE c public.corretores%ROWTYPE; cfg public.ncrm_operacao_config%ROWTYPE;
        local_ts timestamp; local_d date; local_t time; atual boolean; compareceu boolean;
        conectado boolean; visita_pendente integer; suspenso_ate timestamptz;
BEGIN
  SELECT * INTO c FROM public.corretores WHERE id=p_corretor_id;
  IF c.id IS NULL OR coalesce(c.ativo,false) IS NOT TRUE THEN
    RETURN jsonb_build_object('elegivel',false,'motivo','corretor_inativo'); END IF;
  SELECT * INTO cfg FROM public.ncrm_operacao_config WHERE id=true;
  local_ts:=p_agora AT TIME ZONE cfg.timezone; local_d:=local_ts::date; local_t:=local_ts::time;
  conectado:=EXISTS(SELECT 1 FROM public.instancias i WHERE i.corretor_id=c.id
    AND coalesce(i.ativa,true) AND coalesce(i.conectada,false) AND i.status_dapi='connected');
  IF NOT conectado THEN RETURN jsonb_build_object('elegivel',false,'motivo','dapi_desconectada'); END IF;
  SELECT max(s.fim_em) INTO suspenso_ate FROM public.ncrm_corretor_suspensao s
    WHERE s.corretor_id=c.id AND s.revogada_em IS NULL AND s.inicio_em<=p_agora AND s.fim_em>p_agora;
  IF suspenso_ate IS NOT NULL THEN RETURN jsonb_build_object('elegivel',false,'motivo','suspenso','ate',suspenso_ate); END IF;

  SELECT count(*) INTO visita_pendente FROM public.visitas v
   WHERE v.corretor_id=c.id AND v.criado_em>=cfg.corte_feedback_visita
     AND v.status='realizada' AND v.resultado IS NULL
     AND (v.data+coalesce(nullif(v.hora_fim::text,''),nullif(v.hora_inicio::text,''),'18:00')::time) AT TIME ZONE cfg.timezone
           < p_agora-make_interval(mins=>cfg.feedback_visita_min);
  IF visita_pendente>0 THEN RETURN jsonb_build_object('elegivel',false,'motivo','feedback_visita_pendente','quantidade',visita_pendente); END IF;

  atual:=coalesce(c.no_escritorio,false) AND c.ultima_presenca IS NOT NULL
    AND c.ultima_presenca>p_agora-make_interval(mins=>cfg.presenca_ttl_min);
  compareceu:=EXISTS(SELECT 1 FROM public.corretor_presencas cp WHERE cp.corretor_id=c.id AND cp.dia=local_d);
  IF local_t>=cfg.horario_oficial_inicio AND local_t<cfg.horario_oficial_fim THEN
    IF NOT (coalesce(c.online,false) OR atual) THEN
      RETURN jsonb_build_object('elegivel',false,'motivo','presenca_nao_confirmada','periodo','oficial'); END IF;
    RETURN jsonb_build_object('elegivel',true,'motivo','ok','periodo','oficial');
  END IF;
  -- Fora do horário: quem ainda está no escritório recebe; depois que o último
  -- sai, os leads ficam disponíveis para quem compareceu no dia, sem aceite.
  IF EXISTS(SELECT 1 FROM public.corretores cx WHERE coalesce(cx.ativo,false)
      AND coalesce(cx.no_escritorio,false) AND cx.ultima_presenca>p_agora-make_interval(mins=>cfg.presenca_ttl_min)) THEN
    IF NOT atual THEN RETURN jsonb_build_object('elegivel',false,'motivo','fora_horario_nao_presente','periodo','remoto'); END IF;
    RETURN jsonb_build_object('elegivel',true,'motivo','presente_fora_horario','periodo','remoto');
  END IF;
  IF NOT compareceu THEN RETURN jsonb_build_object('elegivel',false,'motivo','nao_compareceu_no_dia','periodo','remoto'); END IF;
  RETURN jsonb_build_object('elegivel',true,'motivo','compareceu_no_dia','periodo','remoto','cobranca_5min',false);
END $fn$;
REVOKE ALL ON FUNCTION public.ncrm_corretor_elegibilidade(bigint,timestamptz) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.ncrm_corretor_elegibilidade(bigint,timestamptz) TO service_role;

CREATE OR REPLACE FUNCTION public.corretor_pode_receber(p_id bigint)
RETURNS boolean LANGUAGE sql STABLE SET search_path='' AS $fn$
  SELECT coalesce((public.ncrm_corretor_elegibilidade(p_id,now())->>'elegivel')::boolean,false);
$fn$;
REVOKE ALL ON FUNCTION public.corretor_pode_receber(bigint) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.corretor_pode_receber(bigint) TO service_role;

-- SLA de 5 minutos estritamente no horário oficial. À noite o lead continua
-- com quem recebeu; não existe aceite nem punição por não chamar de madrugada.
UPDATE public.ncrm_sla_redistribuicao_config SET tolerancia_min=5,atualizado_em=now() WHERE id=true;

-- Presença oficial até 18:30, como definido pela operação.
UPDATE public.distribuicao_config SET janela_inicio='09:30',janela_fim='18:30',receber_ate='18:30',atualizado_em=now() WHERE id=1;
UPDATE public.presenca_config SET hora_inicio='09:30',hora_fim='18:30',intervalo_min=15,atualizado_em=now() WHERE id=1;

-- Prazo exibido para lead recebido fora do horário. Ele fica atribuído e pode
-- ser chamado imediatamente, mas não nasce atrasado durante a madrugada.
CREATE OR REPLACE FUNCTION public.ncrm_primeira_abordagem_prazo(p_agora timestamptz DEFAULT now())
RETURNS timestamptz LANGUAGE plpgsql STABLE SET search_path='' AS $fn$
DECLARE cfg public.ncrm_operacao_config%ROWTYPE; v_local timestamp; v_alvo timestamp;
BEGIN
  SELECT * INTO cfg FROM public.ncrm_operacao_config WHERE id=true;
  v_local:=p_agora AT TIME ZONE cfg.timezone;
  IF v_local::time>=cfg.horario_oficial_inicio AND v_local::time<cfg.horario_oficial_fim THEN
    RETURN p_agora+make_interval(mins=>cfg.primeira_abordagem_min);
  END IF;
  v_alvo:=CASE WHEN v_local::time<cfg.horario_oficial_inicio
    THEN v_local::date+cfg.horario_oficial_inicio
    ELSE (v_local::date+1)+cfg.horario_oficial_inicio END;
  RETURN v_alvo AT TIME ZONE cfg.timezone;
END $fn$;
REVOKE ALL ON FUNCTION public.ncrm_primeira_abordagem_prazo(timestamptz) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.ncrm_primeira_abordagem_prazo(timestamptz) TO service_role;

CREATE OR REPLACE FUNCTION ncrm_private.normalizar_prazo_lead_novo()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $fn$
BEGIN
  IF NEW.etapa='novo' AND NEW.saida IS NULL THEN
    NEW.momento_codigo:='PRIMEIRA_ABORDAGEM';
    NEW.proxima_acao_tipo:='tentativa_cadencia';
    NEW.proxima_acao_titulo:='Fazer a primeira abordagem';
    NEW.proxima_acao_em:=public.ncrm_primeira_abordagem_prazo(now());
  END IF;
  RETURN NEW;
END $fn$;
REVOKE ALL ON FUNCTION ncrm_private.normalizar_prazo_lead_novo() FROM PUBLIC,anon,authenticated;
DROP TRIGGER IF EXISTS ncrm_estado_prazo_lead_novo ON public.ncrm_estado;
CREATE TRIGGER ncrm_estado_prazo_lead_novo BEFORE INSERT ON public.ncrm_estado
FOR EACH ROW EXECUTE FUNCTION ncrm_private.normalizar_prazo_lead_novo();

-- A roleta antiga possui três caminhos de fallback. O patch é mecânico e
-- falha fechado se o corpo auditado mudar; nenhum candidato sem elegibilidade
-- ou D-API saudável pode reaparecer por um caminho alternativo.
DO $guard$
DECLARE v_oid regprocedure:='public.motor_roleta(bigint,text,text,jsonb,bigint,bigint,jsonb,boolean,boolean,jsonb)'::regprocedure;
        v_def text; v_ancora text;
BEGIN
  SELECT pg_get_functiondef(v_oid::oid) INTO v_def;
  IF strpos(v_def,'NCRM31_ELEGIBILIDADE_E_DAPI')>0 THEN RETURN; END IF;
  IF md5(v_def)<>'5ae3ab53bedbd181692dd82540fb84fb' AND strpos(v_def,'NCRM_TEST_STUB_ROLL')=0 THEN
    RAISE EXCEPTION 'motor_roleta_checksum_divergente'; END IF;
  v_ancora:='where public.nome_normalizado(c.nome) = public.nome_normalizado(it->>''corretor'') and coalesce(c.ativo,true)=true';
  IF strpos(v_def,v_ancora)=0 THEN RAISE EXCEPTION 'motor_roleta_ancora_candidatos_ausente'; END IF;
  v_def:=replace(v_def,v_ancora,v_ancora||E'\n          and public.corretor_pode_receber(c.id) /* NCRM31_ELEGIBILIDADE_E_DAPI */');
  v_ancora:='_fallback := true; _cands := _cands_all;';
  IF strpos(v_def,v_ancora)=0 THEN RAISE EXCEPTION 'motor_roleta_ancora_fallback_ausente'; END IF;
  v_def:=replace(v_def,v_ancora,$patch$insert into motor_execucoes(automacao_id,automacao_nome,bloco_id,evento,status,lead_nome,lead_telefone,detalhe)
    values(p_auto,p_nome,p_bloco,'distribuicao','alerta',p_lead->>'nome',v_tel,'Distribuir: nenhum corretor elegivel com D-API conectada');
    return null; /* NCRM31_SEM_FALLBACK_DESCONECTADO */$patch$);
  EXECUTE v_def;
END $guard$;

-- Os cinco minutos só são fiscalizados na janela oficial. Fora dela o lead
-- permanece com o corretor e pode ser chamado na hora ou no próximo expediente.
DO $guard$
DECLARE v_oid regprocedure:='ncrm_private.sla_redistribuir(integer)'::regprocedure;
        v_def text; v_ancora text;
BEGIN
  SELECT pg_get_functiondef(v_oid::oid) INTO v_def;
  IF strpos(v_def,'NCRM31_SLA_SOMENTE_OFICIAL')>0 THEN RETURN; END IF;
  IF md5(v_def)<>'bc9eb203366730ff46123d8166513805' THEN
    RAISE EXCEPTION 'sla_redistribuir_checksum_divergente'; END IF;
  v_ancora:='IF cfg IS NULL OR cfg.ativo IS NOT TRUE THEN RETURN 0; END IF;';
  IF strpos(v_def,v_ancora)=0 THEN RAISE EXCEPTION 'sla_redistribuir_ancora_ausente'; END IF;
  v_def:=replace(v_def,v_ancora,v_ancora||$patch$
  IF NOT EXISTS (SELECT 1 FROM public.ncrm_operacao_config op WHERE op.id=true
    AND (now() AT TIME ZONE op.timezone)::time >= op.horario_oficial_inicio
    AND (now() AT TIME ZONE op.timezone)::time < op.horario_oficial_fim) THEN
    RETURN 0; /* NCRM31_SLA_SOMENTE_OFICIAL */
  END IF;$patch$);
  EXECUTE v_def;
END $guard$;

-- Pescar do Aquário obedece exatamente a mesma elegibilidade da roleta. O
-- atendimento entra no fluxo normal no ciclo seguinte de entrada/reconciliação.
DO $guard$
DECLARE v_oid regprocedure; v_def text; v_ancora text;
BEGIN
  v_oid:='public.aquario_pescar()'::regprocedure;
  SELECT pg_get_functiondef(v_oid::oid) INTO v_def;
  IF strpos(v_def,'NCRM31_AQUARIO_ELEGIVEL')=0 THEN
    IF md5(v_def)<>'12968a66692828d14b17b9b30b58c9d8' AND strpos(v_def,'NCRM_TEST_STUB_ROLL')=0 THEN RAISE EXCEPTION 'aquario_pescar_checksum_divergente'; END IF;
    v_ancora:='  if v_corretor is null then'||E'\n'||
      '    return jsonb_build_object(''ok'', false, ''error'', ''Seu usuário não está vinculado a um corretor ativo.'');'||E'\n'||
      '  end if;';
    IF strpos(v_def,v_ancora)=0 THEN RAISE EXCEPTION 'aquario_pescar_ancora_ausente'; END IF;
    v_def:=replace(v_def,v_ancora,v_ancora||$patch$

  if not public.corretor_pode_receber(v_corretor) then
    return jsonb_build_object('ok',false,'error','Você está temporariamente sem acesso a novos leads. Confira presença, WhatsApp e visitas pendentes.'); /* NCRM31_AQUARIO_ELEGIVEL */
  end if;$patch$);
    EXECUTE v_def;
  END IF;

  v_oid:='public.pescar_lead_aquario(bigint)'::regprocedure;
  SELECT pg_get_functiondef(v_oid::oid) INTO v_def;
  IF strpos(v_def,'NCRM31_AQUARIO_ELEGIVEL')=0 THEN
    IF md5(v_def)<>'53090e4c1e984dfd0e7171e54a862168' AND strpos(v_def,'NCRM_TEST_STUB_ROLL')=0 THEN RAISE EXCEPTION 'pescar_lead_checksum_divergente'; END IF;
    v_ancora:='  if v_corretor is null then raise exception ''Seu usuário não está vinculado a um corretor ativo.'' using errcode = ''42501''; end if;';
    IF strpos(v_def,v_ancora)=0 THEN RAISE EXCEPTION 'pescar_lead_ancora_ausente'; END IF;
    v_def:=replace(v_def,v_ancora,v_ancora||E'\n  if not public.corretor_pode_receber(v_corretor) then raise exception ''Você está temporariamente sem acesso a novos leads. Confira presença, WhatsApp e visitas pendentes.'' using errcode = ''42501''; /* NCRM31_AQUARIO_ELEGIVEL */ end if;');
    EXECUTE v_def;
  END IF;
END $guard$;

-- ---------------------------------------------------------------------------
-- 4. Meu Dia e Sara passam a consumir o mesmo contrato
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.ncrm_fila_trabalho_v4(
  p_filtro text DEFAULT 'agora',p_corretor bigint DEFAULT NULL,p_limite int DEFAULT 100
) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path='' AS $fn$
DECLARE v_uid uuid:=auth.uid(); v_lim int:=LEAST(GREATEST(coalesce(p_limite,100),1),300);
        v_admin boolean; v_broker bigint; v_itens jsonb;
BEGIN
  IF v_uid IS NULL THEN RETURN jsonb_build_object('ok',false,'erro','nao_autenticado'); END IF;
  v_admin:=coalesce(public.can_manage_all(),false); v_broker:=public.current_broker_id();
  SELECT coalesce(jsonb_agg(item ORDER BY (item->>'prioridade')::int,
    (item->>'proxima_acao_em')::timestamptz NULLS LAST),'[]'::jsonb) INTO v_itens
  FROM (
    SELECT jsonb_build_object(
      'negocio_id',e.negocio_id,'lead_nome',l.nome,'etapa',e.etapa,'momento_codigo',e.momento_codigo,
      'temperatura',e.temperatura,'corretor_id',n.corretor_id,'corretor_nome',coalesce(u.nome,'—'),
      'proxima_acao_titulo',e.proxima_acao_titulo,'proxima_acao_em',e.proxima_acao_em,
      'respondeu',e.respondeu,'resposta_pendente',e.resposta_pendente,'tentativas_feitas',e.tentativas_feitas,
      'prioridade',CASE WHEN e.resposta_pendente THEN 1 WHEN e.etapa='novo' THEN 2
        WHEN e.proxima_acao_em<now() THEN 3
        WHEN (e.proxima_acao_em AT TIME ZONE 'America/Sao_Paulo')::date=(now() AT TIME ZONE 'America/Sao_Paulo')::date THEN 4 ELSE 5 END,
      'motivo',CASE WHEN e.resposta_pendente THEN 'Cliente respondeu — aguardando você'
        WHEN e.etapa='novo' THEN 'Lead novo — primeira abordagem'
        WHEN e.proxima_acao_em<now() THEN 'Ação atrasada' ELSE 'Ação programada' END,
      'espera_min',greatest(0,extract(epoch FROM(now()-coalesce(e.proxima_acao_em,e.ultima_interacao_em,now())))/60)::numeric(12,1),
      'conduta',public.ncrm_conduta_oficial_v4(e.etapa,e.momento_codigo,e.respondeu,
        e.resposta_pendente,e.tentativas_feitas,e.proxima_acao_em)
    ) item
    FROM public.ncrm_estado e
    JOIN public.negocios n ON n.id=e.negocio_id
    JOIN public.leads l ON l.id=n.lead_id
    LEFT JOIN public.corretores c ON c.id=n.corretor_id
    LEFT JOIN public.usuarios u ON u.id=c.usuario_id
    WHERE e.saida IS NULL
      AND (v_admin OR n.corretor_id=v_broker OR coalesce(public.manages_broker(n.corretor_id),false))
      AND (p_corretor IS NULL OR n.corretor_id=p_corretor)
      AND CASE coalesce(p_filtro,'agora')
        WHEN 'agora' THEN e.resposta_pendente OR e.etapa='novo' OR e.proxima_acao_em<=date_trunc('day',now() AT TIME ZONE 'America/Sao_Paulo') AT TIME ZONE 'America/Sao_Paulo'+interval '1 day'
        WHEN 'vencidos' THEN e.proxima_acao_em<now()
        WHEN 'hoje' THEN (e.proxima_acao_em AT TIME ZONE 'America/Sao_Paulo')::date=(now() AT TIME ZONE 'America/Sao_Paulo')::date
        WHEN 'proximos' THEN e.proxima_acao_em>date_trunc('day',now() AT TIME ZONE 'America/Sao_Paulo') AT TIME ZONE 'America/Sao_Paulo'+interval '1 day'
        WHEN 'respondeu' THEN e.respondeu
        WHEN 'sem_resposta' THEN NOT e.respondeu
        WHEN 'risco' THEN e.proxima_acao_em<now()-interval '24 hours'
        WHEN 'quente' THEN e.temperatura IN ('quente','negociando') ELSE false END
    ORDER BY CASE WHEN e.resposta_pendente THEN 1 WHEN e.etapa='novo' THEN 2 WHEN e.proxima_acao_em<now() THEN 3 ELSE 4 END,
      e.proxima_acao_em NULLS LAST LIMIT v_lim
  ) q;
  RETURN jsonb_build_object('ok',true,'itens',v_itens,'regra','motor_operacional_v4');
END $fn$;
REVOKE ALL ON FUNCTION public.ncrm_fila_trabalho_v4(text,bigint,int) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.ncrm_fila_trabalho_v4(text,bigint,int) TO authenticated;

CREATE OR REPLACE FUNCTION public.ncrm_sara_aplicar_proxima_acao(
  p_negocio_id bigint,p_analise_id bigint,p_acao_codigo text
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $fn$
DECLARE v_uid uuid:=auth.uid(); v_e public.ncrm_estado%ROWTYPE; v_a public.ncrm_sara_analise%ROWTYPE;
        v_cat public.ncrm_acao_padrao%ROWTYPE; v_m public.ncrm_momento_padrao%ROWTYPE;
        v_lead bigint; v_corretor bigint; v_prazo timestamptz;
BEGIN
  IF v_uid IS NULL THEN RETURN jsonb_build_object('ok',false,'erro','nao_autenticado'); END IF;
  IF ncrm_private.pode_operar_negocio(p_negocio_id) IS NOT TRUE THEN RETURN jsonb_build_object('ok',false,'erro','sem_permissao'); END IF;
  SELECT * INTO v_a FROM public.ncrm_sara_analise WHERE id=p_analise_id AND negocio_id=p_negocio_id;
  IF v_a.id IS NULL THEN RETURN jsonb_build_object('ok',false,'erro','analise_inexistente'); END IF;
  IF v_a.analisado_em<now()-interval '30 minutes' THEN RETURN jsonb_build_object('ok',false,'erro','analise_desatualizada'); END IF;
  IF coalesce(v_a.confianca,0)<.70 THEN RETURN jsonb_build_object('ok',false,'erro','revisao_humana','aplicado',false); END IF;
  SELECT * INTO v_cat FROM public.ncrm_acao_padrao WHERE codigo=p_acao_codigo AND ativa;
  SELECT * INTO v_m FROM public.ncrm_momento_padrao WHERE acao_codigo=p_acao_codigo AND ativo ORDER BY ordem LIMIT 1;
  IF v_cat.codigo IS NULL OR v_m.codigo IS NULL THEN RETURN jsonb_build_object('ok',false,'erro','acao_fora_do_catalogo'); END IF;
  SELECT * INTO v_e FROM public.ncrm_estado WHERE negocio_id=p_negocio_id FOR UPDATE;
  IF v_e.negocio_id IS NULL OR v_e.saida IS NOT NULL THEN RETURN jsonb_build_object('ok',false,'erro','estado_indisponivel'); END IF;
  IF v_e.etapa='novo' AND p_acao_codigo<>'PRIMEIRA_ABORDAGEM' THEN RETURN jsonb_build_object('ok',false,'erro','acao_incompativel_com_momento'); END IF;
  IF NOT v_e.respondeu AND v_e.etapa='tentando_contato' AND p_acao_codigo<>'ENVIAR_CADENCIA' THEN RETURN jsonb_build_object('ok',false,'erro','acao_incompativel_com_momento'); END IF;
  IF v_e.resposta_pendente AND p_acao_codigo<>'RESPONDER_E_QUALIFICAR' THEN RETURN jsonb_build_object('ok',false,'erro','cliente_aguardando_resposta'); END IF;
  v_prazo:=greatest(coalesce(v_a.prazo_sugerido,now()+make_interval(mins=>v_cat.sla_min)),now()+interval '1 minute');
  SELECT lead_id,corretor_id INTO v_lead,v_corretor FROM public.negocios WHERE id=p_negocio_id;
  UPDATE public.ncrm_estado SET etapa=v_m.etapa,momento_codigo=v_m.codigo,
    proxima_acao_tipo=v_cat.proxima_acao_tipo,proxima_acao_titulo=v_cat.rotulo,proxima_acao_em=v_prazo,
    versao=v_e.versao+1,atualizado_em=now(),atualizado_por=v_uid,origem_ultima='sara',proxima_acao_origem='sara'
  WHERE negocio_id=p_negocio_id AND versao=v_e.versao;
  IF NOT FOUND THEN RETURN jsonb_build_object('ok',false,'erro','conflito_versao'); END IF;
  INSERT INTO public.ncrm_evento(negocio_id,lead_id,corretor_id_no_evento,workflow_config_id,tipo,resultado,payload,
    origem,executado_por,idempotency_key,estado_versao_antes,estado_versao_apos)
  VALUES(p_negocio_id,v_lead,v_corretor,v_e.workflow_config_id,'classificacao_sara',p_acao_codigo,
    jsonb_build_object('analise_id',p_analise_id,'momento_codigo',v_m.codigo,'prazo',v_prazo),
    'sara',NULL,concat('sara:conduta:',p_analise_id),v_e.versao,v_e.versao+1)
  ON CONFLICT(idempotency_key) WHERE idempotency_key IS NOT NULL DO NOTHING;
  RETURN jsonb_build_object('ok',true,'aplicado',true,'etapa',v_m.etapa,'momento_codigo',v_m.codigo,
    'momento',v_m.rotulo,'acao_codigo',p_acao_codigo,'acao',v_cat.rotulo,'prazo',v_prazo,'versao',v_e.versao+1);
END $fn$;
REVOKE ALL ON FUNCTION public.ncrm_sara_aplicar_proxima_acao(bigint,bigint,text) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.ncrm_sara_aplicar_proxima_acao(bigint,bigint,text) TO authenticated;

-- O runner da Sara organiza o CRM automaticamente, mas apenas dentro do
-- catálogo fechado. Isto NÃO executa a obrigação: não envia mensagem, não
-- agenda visita e não cria proposta/venda. Só grava Momento + Ação + Prazo.
CREATE OR REPLACE FUNCTION public.ncrm_sara_aplicar_conduta_automatica(
  p_negocio_id bigint,p_analise_id bigint,p_momento_codigo text,p_acao_codigo text
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $fn$
DECLARE v_a public.ncrm_sara_analise%ROWTYPE; v_e public.ncrm_estado%ROWTYPE;
        v_m public.ncrm_momento_padrao%ROWTYPE; v_cat public.ncrm_acao_padrao%ROWTYPE;
        v_momento text:=p_momento_codigo; v_acao text:=p_acao_codigo;
        v_lead bigint; v_corretor bigint; v_prazo timestamptz;
BEGIN
  IF coalesce(auth.role(),'')<>'service_role' THEN
    RETURN jsonb_build_object('ok',false,'erro','somente_servico'); END IF;
  IF NOT EXISTS(SELECT 1 FROM public.ncrm_operacao_config WHERE id=true AND sara_organiza_ativa) THEN
    RETURN jsonb_build_object('ok',false,'erro','organizacao_desligada'); END IF;
  SELECT * INTO v_a FROM public.ncrm_sara_analise
   WHERE id=p_analise_id AND negocio_id=p_negocio_id;
  IF v_a.id IS NULL THEN RETURN jsonb_build_object('ok',false,'erro','analise_inexistente'); END IF;
  IF v_a.analisado_em<now()-interval '30 minutes' THEN
    RETURN jsonb_build_object('ok',false,'erro','analise_desatualizada'); END IF;
  IF coalesce(v_a.confianca,0)<.75 THEN
    RETURN jsonb_build_object('ok',false,'erro','confianca_insuficiente'); END IF;
  IF coalesce(jsonb_array_length(v_a.evidencias),0)=0 THEN
    RETURN jsonb_build_object('ok',false,'erro','analise_sem_base'); END IF;

  SELECT * INTO v_e FROM public.ncrm_estado WHERE negocio_id=p_negocio_id FOR UPDATE;
  IF v_e.negocio_id IS NULL OR v_e.saida IS NOT NULL THEN
    RETURN jsonb_build_object('ok',false,'erro','estado_indisponivel'); END IF;
  IF v_a.etapa_atual IS DISTINCT FROM v_e.etapa THEN
    RETURN jsonb_build_object('ok',false,'erro','estado_mudou'); END IF;
  IF v_e.ultima_decisao_humana_em IS NOT NULL AND v_e.ultima_decisao_humana_em>v_a.analisado_em THEN
    RETURN jsonb_build_object('ok',false,'erro','acao_humana_mais_recente'); END IF;

  -- Fatos inequívocos vencem interpretação: lead novo, ausência total de
  -- resposta e cliente aguardando o corretor têm uma única conduta possível.
  IF v_e.etapa='novo' THEN
    v_momento:='PRIMEIRA_ABORDAGEM'; v_acao:='PRIMEIRA_ABORDAGEM';
  ELSIF v_e.etapa='tentando_contato' AND NOT coalesce(v_e.respondeu,false) THEN
    v_momento:='CADENCIA_SEM_RESPOSTA'; v_acao:='ENVIAR_CADENCIA';
  ELSIF coalesce(v_e.resposta_pendente,false) THEN
    v_momento:='CONVERSANDO_QUALIFICANDO'; v_acao:='RESPONDER_E_QUALIFICAR';
  END IF;
  SELECT * INTO v_m FROM public.ncrm_momento_padrao
   WHERE codigo=v_momento AND ativo AND acao_codigo=v_acao;
  SELECT * INTO v_cat FROM public.ncrm_acao_padrao WHERE codigo=v_acao AND ativa;
  IF v_m.codigo IS NULL OR v_cat.codigo IS NULL THEN
    RETURN jsonb_build_object('ok',false,'erro','conduta_fora_do_catalogo'); END IF;
  IF EXISTS(SELECT 1 FROM public.ncrm_evento
    WHERE idempotency_key=concat('sara:auto:',p_analise_id)) THEN
    RETURN jsonb_build_object('ok',true,'ja_aplicado',true); END IF;

  v_prazo:=CASE
    WHEN v_m.codigo='RETORNO_PROGRAMADO' AND v_a.prazo_sugerido>now()
      AND v_a.prazo_sugerido<=now()+interval '5 days' THEN v_a.prazo_sugerido
    WHEN v_m.codigo='VISITA_AGENDADA' AND v_e.proxima_acao_em>now() THEN v_e.proxima_acao_em
    ELSE now()+make_interval(mins=>v_m.sla_min) END;
  SELECT lead_id,corretor_id INTO v_lead,v_corretor FROM public.negocios WHERE id=p_negocio_id;
  UPDATE public.ncrm_estado SET etapa=v_m.etapa,momento_codigo=v_m.codigo,
    proxima_acao_tipo=v_cat.proxima_acao_tipo,proxima_acao_titulo=v_cat.rotulo,
    proxima_acao_em=v_prazo,proxima_acao_motivo=left(coalesce(nullif(btrim(v_a.justificativa),''),v_m.objetivo),400),
    proxima_acao_origem='sara',origem_ultima='sara',versao=v_e.versao+1,
    atualizado_em=now(),atualizado_por=NULL
  WHERE negocio_id=p_negocio_id AND versao=v_e.versao;
  IF NOT FOUND THEN RETURN jsonb_build_object('ok',false,'erro','conflito_versao'); END IF;
  INSERT INTO public.ncrm_evento(negocio_id,lead_id,corretor_id_no_evento,workflow_config_id,
    tipo,resultado,payload,origem,executado_por,idempotency_key,estado_versao_antes,estado_versao_apos)
  VALUES(p_negocio_id,v_lead,v_corretor,v_e.workflow_config_id,'classificacao_sara',v_acao,
    jsonb_build_object('analise_id',p_analise_id,'momento_codigo',v_m.codigo,'prazo',v_prazo,
      'automatico',true,'executou_acao_comercial',false),
    'sara',NULL,concat('sara:auto:',p_analise_id),v_e.versao,v_e.versao+1);
  RETURN jsonb_build_object('ok',true,'aplicado',true,'momento_codigo',v_m.codigo,
    'acao_codigo',v_acao,'prazo',v_prazo,'versao',v_e.versao+1);
END $fn$;
REVOKE ALL ON FUNCTION public.ncrm_sara_aplicar_conduta_automatica(bigint,bigint,text,text)
  FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.ncrm_sara_aplicar_conduta_automatica(bigint,bigint,text,text)
  TO service_role;

COMMIT;
