"use client";
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */

import { useEffect, useMemo, useState } from "react";

type Broker = { id: number; nome: string };
type Lead = { id: number; nome: string | null };
type Deal = { id: number; lead_id: number; corretor_id: number | null };
type Product = { id: string; nome: string };
type Visit = { id: string; lead_id: number | null; negocio_id: number | null; corretor_id: number | null; cliente_nome: string | null; produto: string | null; empreendimento_id: string | null; data: string; hora_inicio: string | null; hora_fim: string | null; local: string | null; observacoes: string | null; com_gerente: boolean; status: string };
type Task = { id: number; lead_id: number | null; corretor_id: number | null; titulo: string; vencimento: string | null; concluida: boolean; prioridade: string };
type CrmData = { brokers: Broker[]; leads: Lead[]; deals: Deal[]; products: Product[]; visits: Visit[]; tasks: Task[] };
type CalendarItem = { id: string; day: number; date: string; time: string; label: string; brokerId: number | null; product: string; status: string; manager: boolean; type: "visit" | "task"; raw: Visit | Task };

const monthNames = ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"];
const weekdays = ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"];

export function CalendarWorkspace({ accessToken }: { accessToken: string }) {
  const now = new Date();
  const [data, setData] = useState<CrmData>({ brokers: [], leads: [], deals: [], products: [], visits: [], tasks: [] });
  const [year, setYear] = useState(now.getFullYear()); const [month, setMonth] = useState(now.getMonth());
  const [broker, setBroker] = useState(""); const [type, setType] = useState(""); const [manager, setManager] = useState(""); const [product, setProduct] = useState(""); const [status, setStatus] = useState("");
  const [selected, setSelected] = useState<CalendarItem | null>(null); const [creating, setCreating] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const [form, setForm] = useState({ dealId: "", productId: "", date: now.toISOString().slice(0, 10), startTime: "10:00", endTime: "11:00", local: "", observations: "", withManager: false, reminder: true });

  async function load() { setLoading(true); setError(""); const response = await fetch("/api/crm", { headers: { Authorization: `Bearer ${accessToken}` } }); const body = await response.json() as CrmData & { error?: string }; if (!response.ok) setError(body.error ?? "Não foi possível carregar a agenda."); else setData(body); setLoading(false); }
  useEffect(() => { void load(); }, [accessToken]);
  const brokerById = useMemo(() => new Map(data.brokers.map((item) => [item.id, item.nome])), [data.brokers]);
  const leadById = useMemo(() => new Map(data.leads.map((item) => [item.id, item.nome ?? `Lead #${item.id}`])), [data.leads]);
  const items = useMemo(() => {
    const visits: CalendarItem[] = data.visits.map((visit) => ({ id: `v-${visit.id}`, day: Number(visit.data.slice(8, 10)), date: visit.data, time: visit.hora_inicio?.slice(0, 5) ?? "—", label: visit.cliente_nome ?? (visit.lead_id ? leadById.get(visit.lead_id) ?? "Visita" : "Visita"), brokerId: visit.corretor_id, product: visit.produto ?? "", status: visit.status, manager: visit.com_gerente, type: "visit", raw: visit }));
    const tasks: CalendarItem[] = data.tasks.filter((task) => task.vencimento).map((task) => { const date = task.vencimento!.slice(0, 10); return { id: `t-${task.id}`, day: Number(date.slice(8, 10)), date, time: task.vencimento!.slice(11, 16) || "—", label: task.titulo, brokerId: task.corretor_id, product: "", status: task.concluida ? "realizada" : "pendente", manager: false, type: "task", raw: task }; });
    return [...visits, ...tasks].filter((item) => Number(item.date.slice(0, 4)) === year && Number(item.date.slice(5, 7)) - 1 === month && (!broker || item.brokerId === Number(broker)) && (!type || item.type === type) && (!manager || (manager === "yes" ? item.manager : !item.manager)) && (!product || item.product === product) && (!status || item.status === status));
  }, [data, leadById, year, month, broker, type, manager, product, status]);
  const byDay = useMemo(() => { const map = new Map<number, CalendarItem[]>(); items.forEach((item) => map.set(item.day, [...(map.get(item.day) ?? []), item].sort((a, b) => a.time.localeCompare(b.time)))); return map; }, [items]);
  const firstDay = new Date(year, month, 1).getDay(); const daysInMonth = new Date(year, month + 1, 0).getDate(); const cells = [...Array(firstDay).fill(null), ...Array.from({ length: daysInMonth }, (_, index) => index + 1)];
  const todayItems = items.filter((item) => item.date === now.toISOString().slice(0, 10));

  function changeMonth(delta: number) { const next = new Date(year, month + delta, 1); setYear(next.getFullYear()); setMonth(next.getMonth()); }
  function clearFilters() { setBroker(""); setType(""); setManager(""); setProduct(""); setStatus(""); }
  async function updateVisitStatus(visitId: string, nextStatus: string) { setNotice(""); const response = await fetch("/api/crm", { method: "PATCH", headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": "application/json" }, body: JSON.stringify({ action: "updateVisitStatus", visitId, status: nextStatus }) }); const body = await response.json() as { error?: string }; if (!response.ok) setNotice(body.error ?? "Não foi possível atualizar."); else { setNotice("Visita atualizada."); setSelected(null); await load(); } }
  async function createVisit() { const deal = data.deals.find((item) => String(item.id) === form.dealId); if (!deal) { setNotice("Selecione um lead com negócio aberto."); return; } const response = await fetch("/api/crm", { method: "PATCH", headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": "application/json" }, body: JSON.stringify({ action: "createVisit", leadId: deal.lead_id, dealId: deal.id, productId: form.productId, date: form.date, startTime: form.startTime, endTime: form.endTime, local: form.local, observations: form.observations, withManager: form.withManager, reminder: form.reminder }) }); const body = await response.json() as { error?: string }; if (!response.ok) setNotice(body.error ?? "Não foi possível agendar."); else { setNotice("Visita agendada."); setCreating(false); await load(); } }

  return <div className="calendar-workspace">
    <header className="workspace-top"><div><h1>Calendário</h1><p>Visitas, tarefas e compromissos da equipe</p></div><button className="calendar-primary" type="button" onClick={() => setCreating(true)}>＋ Nova visita</button></header>
    {loading ? <div className="workspace-loading">Carregando agenda...</div> : error ? <div className="workspace-error">{error}<button type="button" onClick={() => void load()}>Tentar novamente</button></div> : <main className="calendar-main">
      <section className="today-summary"><span>▣</span><div><small>RESUMO DE HOJE</small><strong>{todayItems.length ? `${todayItems.length} compromisso(s) na agenda de hoje` : "Nenhum compromisso agendado para hoje"}</strong></div><i>{data.visits.filter((visit) => visit.status === "agendada").length} visitas futuras</i><i>{data.tasks.filter((task) => !task.concluida).length} tarefas pendentes</i></section>
      <div className="calendar-nav"><button type="button" onClick={() => changeMonth(-1)}>‹</button><strong>{monthNames[month]} {year}</strong><button type="button" onClick={() => changeMonth(1)}>›</button><i /><span><b className="manager-color" /> Gerente acompanha</span><span><b /> Sem gerente</span></div>
      <div className="calendar-filters"><span>▽</span><select aria-label="Corretor" value={broker} onChange={(event) => setBroker(event.target.value)}><option value="">Todos os corretores</option>{data.brokers.map((item) => <option value={item.id} key={item.id}>{item.nome}</option>)}</select><select aria-label="Tipo" value={type} onChange={(event) => setType(event.target.value)}><option value="">Todos os tipos</option><option value="visit">Visitas</option><option value="task">Tarefas</option></select><select aria-label="Acompanhamento" value={manager} onChange={(event) => setManager(event.target.value)}><option value="">Com ou sem gerente</option><option value="yes">Com gerente</option><option value="no">Sem gerente</option></select><select aria-label="Produto" value={product} onChange={(event) => setProduct(event.target.value)}><option value="">Todos os produtos</option>{[...new Set(data.visits.map((visit) => visit.produto).filter(Boolean))].map((item) => <option key={item!}>{item}</option>)}</select><select aria-label="Status" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Todos os status</option><option value="agendada">Agendada</option><option value="confirmada">Confirmada</option><option value="realizada">Realizada</option><option value="cancelada">Cancelada</option><option value="pendente">Pendente</option></select><button type="button" onClick={clearFilters}>× Limpar</button><i /> <b>{items.length} no mês</b></div>
      <section className="calendar-grid"><div className="calendar-weekdays">{weekdays.map((day) => <span key={day}>{day}</span>)}</div><div className="calendar-days">{cells.map((day, index) => day === null ? <div className="calendar-blank" key={`blank-${index}`} /> : <div className={year === now.getFullYear() && month === now.getMonth() && day === now.getDate() ? "calendar-day today" : "calendar-day"} key={day}><strong>{day}</strong><div>{(byDay.get(day) ?? []).map((item) => <button className={`${item.manager ? "with-manager" : ""} ${item.status}`} type="button" onClick={() => setSelected(item)} key={item.id}><span>{item.status === "realizada" ? "✓ " : item.status === "cancelada" ? "× " : ""}{item.time} · {item.label}</span><small>{item.brokerId ? brokerById.get(item.brokerId) ?? "Sem corretor" : item.type === "task" ? "Tarefa" : "Sem corretor"}</small></button>)}</div></div>)}</div></section>
      {notice && <div className="calendar-notice">{notice}</div>}
    </main>}
    {selected && <div className="calendar-modal-layer" onClick={() => setSelected(null)}><aside className="calendar-detail" onClick={(event) => event.stopPropagation()}><header><div><small>{selected.type === "visit" ? "VISITA" : "TAREFA"}</small><h2>{selected.label}</h2><p>{new Date(`${selected.date}T12:00:00`).toLocaleDateString("pt-BR")} · {selected.time}</p></div><button type="button" onClick={() => setSelected(null)}>×</button></header><dl><div><dt>Corretor</dt><dd>{selected.brokerId ? brokerById.get(selected.brokerId) ?? "—" : "—"}</dd></div><div><dt>Produto</dt><dd>{selected.product || "—"}</dd></div><div><dt>Status</dt><dd>{selected.status}</dd></div><div><dt>Acompanhamento</dt><dd>{selected.manager ? "Com gerente" : "Sem gerente"}</dd></div></dl>{selected.type === "visit" && <footer><button type="button" onClick={() => void updateVisitStatus(String((selected.raw as Visit).id), "cancelada")}>Cancelar visita</button><button className="confirm" type="button" onClick={() => void updateVisitStatus(String((selected.raw as Visit).id), "realizada")}>✓ Marcar realizada</button></footer>}</aside></div>}
    {creating && <div className="calendar-modal-layer" onClick={() => setCreating(false)}><form className="calendar-create" onClick={(event) => event.stopPropagation()} onSubmit={(event) => { event.preventDefault(); void createVisit(); }}><header><div><h2>Agendar visita</h2><p>A visita ficará vinculada ao lead e ao produto.</p></div><button type="button" onClick={() => setCreating(false)}>×</button></header><div><label>Lead<select required value={form.dealId} onChange={(event) => setForm({ ...form, dealId: event.target.value })}><option value="">Selecione</option>{data.deals.map((deal) => <option value={deal.id} key={deal.id}>{leadById.get(deal.lead_id) ?? `Lead #${deal.lead_id}`}</option>)}</select></label><label>Produto<select value={form.productId} onChange={(event) => setForm({ ...form, productId: event.target.value })}><option value="">Selecionar depois</option>{data.products.map((item) => <option value={item.id} key={item.id}>{item.nome}</option>)}</select></label><label>Data<input required type="date" value={form.date} onChange={(event) => setForm({ ...form, date: event.target.value })} /></label><label>Início<input required type="time" value={form.startTime} onChange={(event) => setForm({ ...form, startTime: event.target.value })} /></label><label>Fim<input type="time" value={form.endTime} onChange={(event) => setForm({ ...form, endTime: event.target.value })} /></label><label className="wide">Local<input value={form.local} onChange={(event) => setForm({ ...form, local: event.target.value })} placeholder="Preenchido pelo endereço do produto" /></label><label className="wide">Observações<textarea value={form.observations} onChange={(event) => setForm({ ...form, observations: event.target.value })} /></label><label className="check"><input type="checkbox" checked={form.reminder} onChange={(event) => setForm({ ...form, reminder: event.target.checked })} /> Criar lembrete</label><label className="check"><input type="checkbox" checked={form.withManager} onChange={(event) => setForm({ ...form, withManager: event.target.checked })} /> Com gerente</label></div><footer><button type="button" onClick={() => setCreating(false)}>Cancelar</button><button className="confirm" type="submit">Agendar visita</button></footer></form></div>}
  </div>;
}
