"use client";
/* eslint-disable react-hooks/set-state-in-effect */

import { useEffect, useMemo, useState } from "react";

type Scheduled = { id: number; telefone: string; texto: string | null; quando: string; status: string | null; resultado: string | null; corretor_nome: string | null; criado_em: string | null };
type WaEvent = { id: number; evento: string | null; erro: string | null; processado: boolean; recebido_em: string; session_id: string | null };
type NotificationData = { scheduled: Scheduled[]; events: WaEvent[]; error?: string };
type Notification = { id: string; kind: "message" | "system" | "error"; title: string; description: string; detail: string; date: string; status: string };

export function NotificationWorkspace({ accessToken }: { accessToken: string }) {
  const [data, setData] = useState<NotificationData>({ scheduled: [], events: [] }); const [loading, setLoading] = useState(true); const [tab, setTab] = useState<"all" | "messages" | "system" | "errors">("all"); const [query, setQuery] = useState("");
  useEffect(() => { setLoading(true); void fetch("/api/ai-center", { headers: { Authorization: `Bearer ${accessToken}` } }).then(async (response) => ({ response, body: await response.json() as NotificationData })).then(({ response, body }) => { setData(response.ok ? body : { scheduled: [], events: [], error: body.error ?? "Não foi possível carregar." }); setLoading(false); }); }, [accessToken]);
  const notifications = useMemo<Notification[]>(() => [...data.scheduled.map((item) => ({ id: `m-${item.id}`, kind: item.status === "erro" ? "error" as const : "message" as const, title: item.status === "enviado" ? "Mensagem enviada" : item.status === "erro" ? "Falha no envio" : "Mensagem agendada", description: item.telefone, detail: item.resultado || item.texto || "Sem conteúdo", date: item.criado_em || item.quando, status: item.status || "agendada" })), ...data.events.map((item) => ({ id: `e-${item.id}`, kind: item.erro ? "error" as const : "system" as const, title: item.erro ? "Erro de integração" : item.evento || "Evento do WhatsApp", description: item.session_id || "Instância não identificada", detail: item.erro || (item.processado ? "Evento processado" : "Aguardando processamento"), date: item.recebido_em, status: item.processado ? "processado" : "pendente" }))].sort((a, b) => b.date.localeCompare(a.date)), [data]);
  const visible = notifications.filter((item) => (tab === "all" || (tab === "messages" && item.kind === "message") || (tab === "system" && item.kind === "system") || (tab === "errors" && item.kind === "error")) && `${item.title} ${item.description} ${item.detail}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="notification-workspace"><header className="workspace-top"><div><h1>Notificações</h1><p>Alertas de atendimento, mensagens e integrações</p></div><label className="notification-search">⌕<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar notificação..." /></label></header><nav className="notification-tabs"><button className={tab === "all" ? "active" : ""} type="button" onClick={() => setTab("all")}>Todas <b>{notifications.length}</b></button><button className={tab === "messages" ? "active" : ""} type="button" onClick={() => setTab("messages")}>Mensagens</button><button className={tab === "system" ? "active" : ""} type="button" onClick={() => setTab("system")}>Sistema</button><button className={tab === "errors" ? "active" : ""} type="button" onClick={() => setTab("errors")}>Erros</button></nav>{loading ? <div className="workspace-loading">Carregando notificações...</div> : data.error ? <div className="workspace-error">{data.error}</div> : <main className="notification-list">{visible.map((item) => <article key={item.id}><span className={item.kind}>{item.kind === "message" ? "➤" : item.kind === "error" ? "!" : "◆"}</span><div><header><h2>{item.title}</h2><time>{new Date(item.date).toLocaleString("pt-BR")}</time></header><b>{item.description}</b><p>{item.detail}</p></div><mark>{item.status}</mark></article>)}{!visible.length && <div className="notification-empty"><span>✓</span><h2>Nenhuma notificação nesta seleção</h2><p>Os alertas reais do sistema aparecerão aqui.</p></div>}</main>}</div>;
}
